'use strict';
const express=require('express');
const cors=require('cors');
const axios=require('axios');
const cheerio=require('cheerio');
const bencode=require('bncode');
const crypto=require('crypto');
const http=require('http');
const https=require('https');

const PORT=Number(process.env.PORT||7000);
const BASE='https://sktorrent.eu';
const SEARCH=`${BASE}/torrent/torrents_v2.php`;
const TTL=Number(process.env.CACHE_TTL_SECONDS||600)*1000;
const META_TTL=6*60*60*1000;
const PAGE_SIZE=40;
const CAT={DABING:1,KRESLENE:5,SERIES:16,CONCERTS:26,UHD:43};
const cache=new Map();
const httpAgent=new http.Agent({keepAlive:true,maxSockets:40});
const httpsAgent=new https.Agent({keepAlive:true,maxSockets:40});

const CATS=[
 ['movie','skt-novinky-dabing-filmy','🆕 SKT: Novinky CZ/SK dabing – filmy'],
 ['series','skt-novinky-dabing-serialy','🆕 SKT: Novinky CZ/SK dabing – seriály'],
 ['series','skt-serialy-czsk','🇨🇿🇸🇰 SKT: Seriály – CZ/SK dabing'],
 ['movie','skt-4k-uhd-czsk','💎 SKT: 4K / UHD CZ/SK'],
 ['movie','skt-filmove-novinky','🎬 SKT: Filmové novinky'],
 ['movie','skt-posledne-filmy','🕒 SKT: Posledné pridané filmy'],
 ['series','skt-posledne-serialy','🕒 SKT: Posledné pridané seriály'],
 ['movie','skt-nove-koncerty','🎤 SKT: Nové koncerty'],
 ['movie','skt-posledne-koncerty','🎶 SKT: Posledné pridané koncerty'],
 ['movie','skt-4k-uhd-koncerty','✨ SKT: 4K / UHD koncerty']
].map(([type,id,name])=>({type,id,name}));

const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const nodiac=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const abs=u=>{try{return u?new URL(u,SEARCH).href:null}catch{return null}};
const dec=t=>{try{return t&&t!=='default'?JSON.parse(Buffer.from(t,'base64url').toString('utf8')):{}}catch{return{}}};
const log=(...a)=>console.log(new Date().toISOString(),...a);
async function cached(k,ttl,fn){const h=cache.get(k);if(h&&h.e>Date.now())return h.v;const v=await fn();cache.set(k,{v,e:Date.now()+ttl});return v}
const pages=c=>Math.max(1,Math.min(20,Number(c.pages||8)||8));
function client(c={}){return axios.create({timeout:12000,maxRedirects:5,httpAgent,httpsAgent,headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36','Accept-Language':'sk,cs;q=0.9,en;q=0.7',Referer:BASE+'/',...(c.uid&&c.pass?{Cookie:`uid=${c.uid}; pass=${c.pass}`}:{})}})}
function dateFrom(t){const m=String(t).match(/Pridany\s+(\d{1,2})\/(\d{1,2})\/(\d{4})/i);return m?new Date(Date.UTC(+m[3],+m[2]-1,+m[1],12)):null}
function yearFrom(t){const y=new Date().getUTCFullYear(),a=[...String(t).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(m=>+m[1]).filter(x=>x<=y+1);return a.at(-1)||null}
function displayTitle(s){return clean(s).replace(/^Stiahni si\s*/i,'').replace(/\s*=\s*CSFD\s*\d+%.*$/i,'').trim()||'SKTorrent'}
function stripCatPrefix(name,cat){let n=displayTitle(name),c=clean(cat);if(c&&n.toLowerCase().startsWith(c.toLowerCase()))n=clean(n.slice(c.length).replace(/^[-:|]+/,' '));return n||displayTitle(name)}
function lookupCandidates(raw){let s=displayTitle(raw)
 .replace(/^((filmy\s+cz\/sk\s+dabing|uhd\s+filmy|filmy\s+hd|filmy\s+kreslene|serial|seri[aá]l|hudebni\s+videa)\s+)/i,' ')
 .replace(/\[[^\]]*\]/g,' ')
 .replace(/\((?:CZ|SK|EN|CZ\/EN|SK\/EN|CZ\/SK|SK\/CZ|CZ\/SK\/EN)[^)]*\)/gi,' ')
 .replace(/\bS\d{1,2}(?:E\d{1,3})?\b/gi,' ')
 .replace(/\b\d{1,2}x\d{1,3}\b/gi,' ')
 .replace(/\b(2160p|1080p|720p|4k|uhd|hdr10\+?|hdr|dolby\s*vision|dv|hevc|x265|x264|web-?dl|webrip|blu-?ray|bdrip|tvrip|remux|h\.?264|h\.?265|full\s*dvdrip)\b/gi,' ')
 .replace(/\s+/g,' ').trim();
 const parts=s.split(/\s+(?:\/|\/\/|\|)\s+/).map(x=>x.trim()).filter(Boolean),out=[];
 for(const p of [...parts,s]){const q=p.replace(/\((?:19\d{2}|20\d{2})(?:\s*[-–]\s*(?:19\d{2}|20\d{2}))?\)/g,' ').replace(/\b(?:19\d{2}|20\d{2})\b/g,' ').replace(/\s+/g,' ').trim();if(q.length>1&&!out.includes(q))out.push(q)}
 return out.slice(0,3)
}
const lookupTitle=n=>lookupCandidates(n)[0]||displayTitle(n);
function posterFromCell($,cell){let out=null;cell.find('img').each((_,im)=>{if(out)return;const el=$(im);for(const k of ['data-src','data-original','data-lazy-src','src']){const u=abs(el.attr(k));if(!u)continue;const l=u.toLowerCase();if(l.includes('/flag/')||l.includes('/flags/')||l.includes('spacer')||l.includes('pixel')||l.endsWith('.gif')||l.includes('category'))continue;out=u;break}});return out}
function parseAnchor($,el,forcedCat=0){const a=$(el),href=a.attr('href')||'',m=href.match(/[?&]id=([^&]+)/);if(!m)return null;const cell=a.closest('td');if(!cell.length)return null;const text=clean(cell.text());let category=clean(cell.find('a[href*="category="]').first().text())||clean(cell.find('b').first().text());if(!category){if(forcedCat===CAT.CONCERTS)category='Hudební videa';if(forcedCat===CAT.SERIES)category='Seriál';if(forcedCat===CAT.DABING)category='Filmy CZ/SK dabing';if(forcedCat===CAT.UHD)category='UHD Filmy';if(forcedCat===CAT.KRESLENE)category='Filmy Kreslené'}let name=clean(a.attr('title'))||clean(a.text())||clean(a.find('img').first().attr('alt'));if(!name||/^(image|cz|sk|en|de|pl|hu)$/i.test(name))return null;name=stripCatPrefix(name,category);const d=dateFrom(text);return{id:m[1],name,category,size:(text.match(/Velkost\s*([^|]+)/i)||[])[1]?.trim()||'?',seeds:+((text.match(/Odosielaju\s*:\s*(\d+)/i)||[])[1]||0),addedDate:d,added:d?d.toISOString().slice(0,10):null,poster:posterFromCell($,cell),year:yearFrom(name),detailUrl:abs(href),downloadUrl:`${BASE}/torrent/download.php?id=${encodeURIComponent(m[1])}`}}
async function fetchPage(p,c={},category=0,search=''){const key=`page:${category}:${p}:${search}:${c.uid?String(c.uid).slice(-6):'g'}`;return cached(key,TTL,async()=>{const r=await client(c).get(SEARCH,{params:{active:0,category,order:'data',by:'DESC',page:p,...(search?{search}:{} )}}),$=cheerio.load(r.data),map=new Map();$('a[href^="details.php"]').each((_,el)=>{const x=parseAnchor($,el,category);if(!x)return;const old=map.get(x.id);if(!old||x.name.length>old.name.length||(!old.poster&&x.poster))map.set(x.id,{...old,...x})});const out=[...map.values()];log(`SKTorrent page=${p} category=${category} search=${search||'-'} parsed=${out.length}`);return out})}
async function recent(c={},wanted=120,category=0,maxPages=null){const out=[],seen=new Set(),limit=maxPages||pages(c);for(let p=0;p<limit;p++){let a=[];try{a=await fetchPage(p,c,category)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if(a.length<10)break;if(out.length>=Math.max(200,wanted*5)&&p>=2)break}return out.sort((a,b)=>(b.addedDate?.getTime()||0)-(a.addedDate?.getTime()||0))}
async function mergeSources(...arrs){const m=new Map();for(const arr of await Promise.all(arrs))for(const x of arr)if(!m.has(x.id))m.set(x.id,x);return [...m.values()].sort((a,b)=>(b.addedDate?.getTime()||0)-(a.addedDate?.getTime()||0))}
async function searchItems(q,c={},maxPages=4){const out=[],seen=new Set();for(let p=0;p<maxPages;p++){let a=[];try{a=await fetchPage(p,c,0,q)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if(a.length<10)break}return out}
const is4k=x=>/\b(2160p|4k|uhd)\b|hdr10\+?|dolby\s*vision|\bDV\b/i.test(x.name);
const isSeries=x=>/seri[aá]l/i.test(x.category);
function isMovie(x){const c=nodiac(x.category).toLowerCase();return !c.includes('serial')&&!c.includes('hudba')&&!c.includes('hudebni videa')&&!c.includes('tv porad')&&!c.includes('sport')&&(c.includes('film')||c.includes('uhd')||c.includes('blu-ray'))}
function isCzSk(x){const t=`${x.category} ${x.name}`;return /filmy\s+cz\s*\/\s*sk\s+dabing/i.test(x.category)||/(?:^|[\s(\[\/_-])(CZ|SK)(?=$|[\s)\]\/, _-])/i.test(t)||/CZ\s*\/\s*(SK|EN)|SK\s*\/\s*(CZ|EN)/i.test(t)}
function isConcert(x){const c=nodiac(x.category).toLowerCase();if(c.includes('hudebni videa'))return true;if(!c.includes('hudba')||/\b(flac|mp3|wavpack|wav|aac|hi-?res)\b/i.test(x.name))return false;return /\b(concert|koncert|live\s+(at|in)|tour|festival|unplugged|ziv[eě])\b/i.test(x.name)&&/\b(2160p|1080p|720p|4k|uhd|blu-?ray|web-?dl|webrip|x26[45]|mkv|mp4)\b/i.test(x.name)}
function isAllowedStreamCategory(x){const c=nodiac(x.category).toLowerCase();return /film|seri|tv porad|dokument|sport|hudebni videa/.test(c)}
const fresh=(x,d=120)=>x.addedDate&&Date.now()-x.addedDate.getTime()<d*864e5;
const newRel=x=>x.year?x.year>=new Date().getUTCFullYear()-1:fresh(x);
async function sourceForCatalog(id,c){switch(id){case'skt-novinky-dabing-filmy':return recent(c,160,CAT.DABING);case'skt-novinky-dabing-serialy':case'skt-serialy-czsk':case'skt-posledne-serialy':return recent(c,220,CAT.SERIES);case'skt-4k-uhd-czsk':return mergeSources(recent(c,160,CAT.UHD),recent(c,160,CAT.DABING));case'skt-nove-koncerty':case'skt-posledne-koncerty':return recent(c,180,CAT.CONCERTS);case'skt-4k-uhd-koncerty':return recent(c,300,CAT.CONCERTS,20);default:return recent(c,220,0)}}
function filter(id,a){switch(id){case'skt-novinky-dabing-filmy':return a.filter(x=>isMovie(x)&&isCzSk(x)&&newRel(x));case'skt-novinky-dabing-serialy':return a.filter(x=>isSeries(x)&&isCzSk(x)&&(fresh(x)||newRel(x)));case'skt-serialy-czsk':return a.filter(x=>isSeries(x)&&isCzSk(x));case'skt-4k-uhd-czsk':return a.filter(x=>isMovie(x)&&isCzSk(x)&&is4k(x));case'skt-filmove-novinky':return a.filter(x=>isMovie(x)&&newRel(x));case'skt-posledne-filmy':return a.filter(isMovie);case'skt-posledne-serialy':return a.filter(isSeries);case'skt-nove-koncerty':return a.filter(x=>isConcert(x)&&newRel(x));case'skt-posledne-koncerty':return a.filter(isConcert);case'skt-4k-uhd-koncerty':return a.filter(x=>isConcert(x)&&is4k(x));default:return[]}}
const nm=s=>nodiac(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
function hitYear(h){return +((String(h.releaseInfo||h.year||'').match(/\b(19\d{2}|20\d{2})\b/)||[])[1]||0)||null}
function pickHit(arr,q,y){const nq=nm(q);let best=null,score=-999;for(const h of arr||[]){const hn=nm(h.name||h.title);let s=hn===nq?100:(hn.includes(nq)||nq.includes(hn)?65:0);const hy=hitYear(h);if(y&&hy)s+=Math.abs(y-hy)<=1?25:-35;if(h.poster)s+=5;if(s>score){score=s;best=h}}return score>=55?best:null}
async function cinemetaSearch(type,q){return cached(`cine-search:${type}:${q.toLowerCase()}`,META_TTL,async()=>{try{const r=await axios.get(`https://v3-cinemeta.strem.io/catalog/${type==='series'?'series':'movie'}/top/search=${encodeURIComponent(q)}.json`,{timeout:5000});return r.data?.metas||[]}catch(e){log('Cinemeta search',q,e.message);return[]}})}
async function findCinemeta(x,type){for(const q of lookupCandidates(x.name)){const h=pickHit(await cinemetaSearch(type,q),q,x.year);if(h)return h}return null}
async function tmdbSearch(x,type,c){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return null;for(const q of lookupCandidates(x.name)){try{const t=type==='series'?'tv':'movie',yr=type==='series'?'first_air_date_year':'year',r=await axios.get(`https://api.themoviedb.org/3/search/${t}`,{timeout:5000,params:{api_key:key,query:q,language:'cs-CZ',include_adult:false,...(x.year?{[yr]:x.year}:{})}}),h=r.data?.results?.[0];if(h){let imdb=null;try{const e=await axios.get(`https://api.themoviedb.org/3/${t}/${h.id}/external_ids`,{timeout:4000,params:{api_key:key}});imdb=e.data?.imdb_id||null}catch{}return{...h,imdb}}}catch(e){log('TMDB',q,e.message)}}return null}
function baseUrl(req){return String(process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'')}
const fallbackPoster=(req,t)=>`${baseUrl(req)}/poster.svg?title=${encodeURIComponent(t||'SKTorrent')}`;
function localMeta(req,x,type,concert=false){const id=type==='series'?`sktseries:${x.id}`:`${concert?'sktc':'skt'}:${x.id}`;return{id,type,name:displayTitle(x.name),poster:x.poster||fallbackPoster(req,x.name),posterShape:'poster',description:[x.category,x.added&&`Pridané ${x.added}`,x.size,`${x.seeds} seed`].filter(Boolean).join(' • '),releaseInfo:x.year?String(x.year):x.added||undefined,genres:concert?['Concert']:undefined,...(type==='movie'?{behaviorHints:{defaultVideoId:id}}:{})}}
async function resolveMeta(req,x,type,c,concert=false){let meta=localMeta(req,x,type,concert),cine=await findCinemeta(x,type);if(cine){meta={...meta,...cine,id:cine.id||meta.id,type,poster:cine.poster||meta.poster,background:cine.background||meta.background,description:cine.description||meta.description,releaseInfo:cine.releaseInfo||meta.releaseInfo};if(type==='movie')meta.behaviorHints={...(cine.behaviorHints||{}),defaultVideoId:meta.id}}
 const t=await tmdbSearch(x,type,c);if(t){const date=t.release_date||t.first_air_date;meta={...meta,id:t.imdb||meta.id,name:t.title||t.name||meta.name,poster:t.poster_path?`https://image.tmdb.org/t/p/w500${t.poster_path}`:meta.poster,background:t.backdrop_path?`https://image.tmdb.org/t/p/original${t.backdrop_path}`:meta.background,description:t.overview||meta.description,releaseInfo:date?.slice(0,4)||meta.releaseInfo,imdbRating:t.vote_average?Number(t.vote_average).toFixed(1):meta.imdbRating};if(type==='movie')meta.behaviorHints={...(meta.behaviorHints||{}),defaultVideoId:meta.id}}
 return meta}
async function mapLimit(a,n,fn){const out=new Array(a.length);let i=0;async function w(){for(;;){const j=i++;if(j>=a.length)return;try{out[j]=await fn(a[j],j)}catch(e){log('mapLimit',e.message);out[j]=null}}}await Promise.all(Array.from({length:Math.min(n,Math.max(1,a.length))},w));return out.filter(Boolean)}
function dedupMetas(a){const m=new Map();for(const x of a){const k=x.id||`${x.type}:${nm(x.name)}:${x.releaseInfo||''}`;if(!m.has(k))m.set(k,x)}return [...m.values()]}
function manifest(){return{id:'community.sktorrent.catalogs',version:'1.2.0',name:'SKTorrent Katalógy',description:'SKTorrent katalógy s IMDb/TMDB kompatibilnou metadata logikou, CZ/SK filmami, seriálmi a koncertmi.',resources:[{name:'catalog',types:['movie','series']},{name:'meta',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:']},{name:'stream',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:']}],types:['movie','series'],catalogs:CATS.map(c=>({...c,extra:[{name:'skip',isRequired:false}]})),idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:'],behaviorHints:{configurable:true,configurationRequired:false}}}
const skipOf=s=>Math.max(0,+((decodeURIComponent(String(s||'')).match(/skip=(\d+)/)||[])[1]||0));
async function catalog(req,res,c){const spec=CATS.find(x=>x.type===req.params.type&&x.id===req.params.id);if(!spec)return res.status(404).json({metas:[]});const sk=skipOf(req.params.extra),raw=filter(spec.id,await sourceForCatalog(spec.id,c));const concert=spec.id.includes('koncert');const batch=raw.slice(sk,sk+Math.max(PAGE_SIZE*2,60));let metas=await mapLimit(batch,7,x=>resolveMeta(req,x,spec.type,c,concert));metas=dedupMetas(metas).slice(0,PAGE_SIZE);log(`catalog ${spec.id} raw=${raw.length} batch=${batch.length} metas=${metas.length} standard=${metas.filter(m=>/^tt\d+$/.test(m.id)||m.id.startsWith('tmdb:')).length}`);res.json({metas})}
async function cinemetaMeta(type,id){try{const r=await axios.get(`https://v3-cinemeta.strem.io/meta/${type}/${id}.json`,{timeout:6000});return r.data?.meta||null}catch{return null}}
async function tmdbMeta(type,id,c){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return null;const n=Number(String(id).replace(/^tmdb:/,''));if(!n)return null;try{const t=type==='series'?'tv':'movie',r=await axios.get(`https://api.themoviedb.org/3/${t}/${n}`,{timeout:5000,params:{api_key:key,language:'cs-CZ'}}),z=r.data,date=z.release_date||z.first_air_date;return{id:`tmdb:${n}`,type,name:z.title||z.name,poster:z.poster_path?`https://image.tmdb.org/t/p/w500${z.poster_path}`:undefined,background:z.backdrop_path?`https://image.tmdb.org/t/p/original${z.backdrop_path}`:undefined,description:z.overview,releaseInfo:date?.slice(0,4)}}catch{return null}}
async function meta(req,res,c){const{id,type}=req.params;if(/^tt\d+$/.test(id)){const m=await cinemetaMeta(type,id);return res.json({meta:m})}if(id.startsWith('tmdb:'))return res.json({meta:await tmdbMeta(type,id,c)});if((type==='movie')&&(id.startsWith('skt:')||id.startsWith('sktc:'))){const tid=id.split(':')[1],all=await mergeSources(recent(c,220,0),recent(c,120,CAT.CONCERTS)),x=all.find(v=>v.id===tid);return res.json({meta:x?await resolveMeta(req,x,'movie',c,id.startsWith('sktc:')):null})}res.json({meta:null})}
async function torrentData(x,c){if(!c.uid||!c.pass)throw Error('Nastav SKTorrent uid/pass cez /configure.');return cached(`tor:${x.id}:${String(c.uid).slice(-6)}`,864e5,async()=>{const r=await client(c).get(x.downloadUrl,{responseType:'arraybuffer',timeout:15000}),buf=Buffer.from(r.data);if(buf.slice(0,100).toString().match(/<html|<!doctype/i))throw Error('SKTorrent vrátil HTML namiesto .torrent – skontroluj uid/pass.');const t=bencode.decode(buf),hash=crypto.createHash('sha1').update(bencode.encode(t.info)).digest('hex'),files=t.info.files?t.info.files.map((f,i)=>({index:i,path:(f['path.utf-8']||f.path||[]).map(p=>Buffer.from(p).toString()).join('/'),length:Number(f.length||0)})):[{index:0,path:Buffer.from(t.info['name.utf-8']||t.info.name||'video').toString(),length:Number(t.info.length||0)}];return{hash,files}})}
const videoFiles=a=>a.filter(f=>/\.(mkv|mp4|avi|m4v|ts|m2ts|mov|wmv|webm)$/i.test(f.path));
function episode(n){const s=nodiac(n);let m=s.match(/\bS(\d{1,2})[ ._-]*E(\d{1,3})\b/i);if(m)return{season:+m[1],episode:+m[2]};m=s.match(/\b(\d{1,2})x(\d{1,3})\b/i);return m?{season:+m[1],episode:+m[2]}:{season:null,episode:null}}
function targetYear(meta){return +((String(meta?.releaseInfo||meta?.year||'').match(/\b(19\d{2}|20\d{2})\b/)||[])[1]||0)||null}
function scoreCandidate(x,target,type,season=null,ep=null){if(!isAllowedStreamCategory(x))return-999;const q=nm(target.name),cand=lookupCandidates(x.name).map(nm),cn=nm(x.name);let s=cand.includes(q)?100:(cand.some(z=>z&&q&&(z.includes(q)||q.includes(z)))||cn.includes(q)?65:0);const y=targetYear(target);if(type==='movie'&&y&&x.year)s+=Math.abs(y-x.year)<=1?25:-45;if(isCzSk(x))s+=18;if(x.seeds)s+=Math.min(15,Math.log2(x.seeds+1)*3);if(type==='series'){if(!/seri|tv porad|dokument/i.test(nodiac(x.category)))s-=20;if(season&&ep){const e=episode(x.name);if(e.season===season&&e.episode===ep)s+=55;else if(e.season===season&&e.episode==null)s+=15;else if(e.season&&e.season!==season)s-=35}}else if(isMovie(x))s+=10;return s}
async function targetFromStandard(type,id,c){if(/^tt\d+/.test(id)){const base=id.split(':')[0],m=await cinemetaMeta(type,base);if(m)return m}if(id.startsWith('tmdb:'))return tmdbMeta(type,id,c);return null}
async function streamsForStandard(type,id,c){const bits=id.split(':'),base=/^tt\d+$/.test(bits[0])?bits[0]:(id.startsWith('tmdb:')?bits.slice(0,2).join(':'):id),season=/^tt\d+$/.test(bits[0])&&bits.length>=3?+bits[1]:null,ep=/^tt\d+$/.test(bits[0])&&bits.length>=3?+bits[2]:null,target=await targetFromStandard(type,base,c);if(!target)return[];const qs=[target.name,target.originalName,target.name&&String(target.name).split(':')[0]].filter(Boolean),all=[];for(const q of [...new Set(qs)]){try{all.push(...await searchItems(q,c,4))}catch{}}const uniq=[...new Map(all.map(x=>[x.id,x])).values()],ranked=uniq.map(x=>({x,s:scoreCandidate(x,target,type,season,ep)})).filter(z=>z.s>=55).sort((a,b)=>b.s-a.s).slice(0,8);const made=await mapLimit(ranked,3,async z=>{const td=await torrentData(z.x,c),vf=videoFiles(td.files);let f;if(type==='series'&&season&&ep)f=vf.find(v=>{const e=episode(v.path);return e.season===season&&e.episode===ep});f=f||[...vf].sort((a,b)=>b.length-a.length)[0];if(!f)return null;return{name:`SKTorrent • ${is4k(z.x)?'4K/UHD':/1080p/i.test(z.x.name)?'1080p':/720p/i.test(z.x.name)?'720p':'Video'}`,title:`${z.x.name}\n${z.x.size} • ${z.x.seeds} seed`,infoHash:td.hash,fileIdx:f.index,behaviorHints:{filename:f.path,bingeGroup:`skt-${base}`}}});return made.filter(Boolean)}
async function stream(req,res,c){if(!c.uid||!c.pass)return res.json({streams:[{name:'SKTorrent – konfigurácia',title:'Nastav uid/pass cez /configure.',externalUrl:`${baseUrl(req)}/configure`} ]});const{id,type}=req.params;if(/^tt\d+/.test(id)||id.startsWith('tmdb:')){try{return res.json({streams:await streamsForStandard(type,id,c)})}catch(e){return res.json({streams:[{name:'SKTorrent – chyba',title:e.message,externalUrl:`${baseUrl(req)}/configure`} ]})}}const p=id.split(':'),tid=p[1],all=await mergeSources(recent(c,220,0),recent(c,160,CAT.CONCERTS)),x=all.find(v=>v.id===tid);if(!x)return res.json({streams:[]});try{const td=await torrentData(x,c),vf=videoFiles(td.files),f=[...vf].sort((a,b)=>b.length-a.length)[0];if(!f)return res.json({streams:[]});res.json({streams:[{name:`SKTorrent • ${is4k(x)?'4K/UHD':/1080p/i.test(x.name)?'1080p':'Video'}`,title:`${x.name}\n${x.size} • ${x.seeds} seed`,infoHash:td.hash,fileIdx:f.index,behaviorHints:{filename:f.path,bingeGroup:`skt-${tid}`}}]})}catch(e){res.json({streams:[{name:'SKTorrent – chyba',title:e.message,externalUrl:`${baseUrl(req)}/configure`} ]})}}

const app=express();app.set('trust proxy',1);app.use(cors());app.use(express.urlencoded({extended:true}));app.use(express.json());
app.get('/health',(_q,r)=>r.json({ok:true,addon:'SKTorrent Katalógy',version:'1.2.0',catalogs:CATS.length,standardIds:true,categories:CAT,at:new Date().toISOString()}));
app.get('/poster.svg',(q,r)=>r.type('svg').send(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900"><rect width="100%" height="100%" fill="#171717"/><text x="300" y="390" text-anchor="middle" fill="white" font-family="Arial" font-size="42" font-weight="700">SKTorrent</text><text x="300" y="450" text-anchor="middle" fill="#ddd" font-family="Arial" font-size="20">${esc(String(q.query.title||'').slice(0,42))}</text></svg>`));
app.get('/configure',(req,res)=>{const base=baseUrl(req);res.type('html').send(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{font:16px system-ui;background:#101114;color:#eee;max-width:720px;margin:35px auto;padding:18px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:6px 0 15px;border-radius:9px}input{background:#1b1d22;color:#fff;border:1px solid #444}button{font-weight:700}code{word-break:break-all}</style><h1>SKTorrent Katalógy v1.2</h1><p>Metadata používajú IMDb ID podobne ako RZ SkT katalógy. uid/pass sú potrebné na prehrávanie. TMDB key je voliteľný pre lepšie české názvy a popisy.</p><input id=u placeholder="uid"><input id=p type=password placeholder="pass"><input id=t type=password placeholder="TMDB API key (voliteľné)"><input id=pg type=number min=1 max=20 value=8><button onclick="go()">Vytvoriť manifest</button><p id=o></p><script>function go(){let c={uid:u.value.trim(),pass:p.value.trim(),tmdbKey:t.value.trim(),pages:+pg.value||8},x=btoa(unescape(encodeURIComponent(JSON.stringify(c)))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,''),m='${base}/'+x+'/manifest.json';o.innerHTML='<a href="stremio://'+m.replace(/^https?:\\/\\//,'')+'">Inštalovať do Stremio</a><br><br><code>'+m+'</code>'}</script>`)});
app.get('/manifest.json',(_q,r)=>r.json(manifest()));app.get('/:token/manifest.json',(_q,r)=>r.json(manifest()));
for(const pre of ['', '/:token']){app.get(`${pre}/catalog/:type/:id.json`,async(q,r)=>{try{await catalog(q,r,pre?dec(q.params.token):{})}catch(e){log('catalog',e.message);r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/catalog/:type/:id/:extra.json`,async(q,r)=>{try{await catalog(q,r,pre?dec(q.params.token):{})}catch(e){log('catalog',e.message);r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/meta/:type/:id.json`,async(q,r)=>{try{await meta(q,r,pre?dec(q.params.token):{})}catch(e){r.status(502).json({meta:null,error:e.message})}});app.get(`${pre}/stream/:type/:id.json`,async(q,r)=>{try{await stream(q,r,pre?dec(q.params.token):{})}catch(e){r.status(502).json({streams:[],error:e.message})}})}
app.get('/debug/catalog/:type/:id',async(q,r)=>{try{const spec=CATS.find(x=>x.type===q.params.type&&x.id===q.params.id);if(!spec)return r.status(404).json({ok:false});const raw=filter(spec.id,await sourceForCatalog(spec.id,{}));const sample=await mapLimit(raw.slice(0,10),5,x=>resolveMeta(q,x,spec.type,{},spec.id.includes('koncert')));r.json({ok:true,id:spec.id,raw:raw.length,sample:sample.map(m=>({id:m.id,name:m.name,poster:m.poster,releaseInfo:m.releaseInfo}))})}catch(e){r.status(502).json({ok:false,error:e.message})}});
app.get('/',(_q,r)=>r.redirect('/configure'));
app.listen(PORT,()=>{log(`SKTorrent addon v1.2 listening on ${PORT}`);setTimeout(async()=>{try{const [d,s,u,k]=await Promise.all([fetchPage(0,{},CAT.DABING),fetchPage(0,{},CAT.SERIES),fetchPage(0,{},CAT.UHD),fetchPage(0,{},CAT.CONCERTS)]);log(`Category self-test dabing=${d.length} series=${s.length} uhd=${u.length} concerts=${k.length}`)}catch(e){log('Category self-test failed',e.message)}},1500)});
