function targetYear(meta){return +((String(meta?.releaseInfo||meta?.year||'').match(/\b(19\d{2}|20\d{2})\b/)||[])[1]||0)||null}
function scoreCandidate(x,target,type,season=null,ep=null){if(!isAllowedStreamCategory(x))return-999;const q=nm(target.name),cand=lookupCandidates(x.name).map(nm),cn=nm(x.name);let s=cand.includes(q)?100:(cand.some(z=>z&&q&&(z.includes(q)||q.includes(z)))||cn.includes(q)?65:0);const y=targetYear(target);if(type==='movie'&&y&&x.year)s+=Math.abs(y-x.year)<=1?25:-45;if(isCzSk(x))s+=18;if(x.seeds)s+=Math.min(15,Math.log2(x.seeds+1)*3);if(type==='series'){if(!/seri|tv porad|dokument/i.test(nodiac(x.category)))s-=20;if(season&&ep){const e=episode(x.name);if(e.season===season&&e.episode===ep)s+=55;else if(e.season===season&&e.episode==null)s+=15;else if(e.season&&e.season!==season)s-=35}}else if(isMovie(x))s+=10;return s}
async function targetFromStandard(type,id,c){if(/^tt\d+/.test(id)){const base=id.split(':')[0],m=await cinemetaMeta(type,base);if(m)return m}if(id.startsWith('tmdb:'))return tmdbMeta(type,id,c);return null}
async function streamsForStandard(type,id,c){const bits=id.split(':'),base=/^tt\d+$/.test(bits[0])?bits[0]:(id.startsWith('tmdb:')?bits.slice(0,2).join(':'):id),season=/^tt\d+$/.test(bits[0])&&bits.length>=3?+bits[1]:null,ep=/^tt\d+$/.test(bits[0])&&bits.length>=3?+bits[2]:null,target=await targetFromStandard(type,base,c);if(!target)return[];const qs=[target.name,target.originalName,target.name&&String(target.name).split(':')[0]].filter(Boolean),all=[];for(const q of [...new Set(qs)]){try{all.push(...await searchItems(q,c,4))}catch{}}const uniq=[...new Map(all.map(x=>[x.id,x])).values()],ranked=uniq.map(x=>({x,s:scoreCandidate(x,target,type,season,ep)})).filter(z=>z.s>=55).sort((a,b)=>b.s-a.s).slice(0,8),streams=[];for(const z of ranked.slice(0,3)){try{const td=await torrentData(z.x),vf=videoFiles(td.files);let f;if(type==='series'&&season&&ep)f=vf.find(v=>{const e=episode(v.path);return e.season===season&&e.episode===ep});f=f||[...vf].sort((a,b)=>b.length-a.length)[0];if(f)streams.push({name:`SKTorrent • ${is4k(z.x)?'4K/UHD':/1080p/i.test(z.x.name)?'1080p':/720p/i.test(z.x.name)?'720p':'Video'}`,title:`${z.x.name}\n${z.x.size} • ${z.x.seeds} seed`,infoHash:td.hash,fileIdx:f.index,behaviorHints:{filename:f.path,bingeGroup:`skt-${base}`}})}catch(e){log('torrent guest',e.message)}}return streams}
async function stream(req,res,c){const{id,type}=req.params;if(/^tt\d+/.test(id)||id.startsWith('tmdb:')){try{return res.json({streams:await streamsForStandard(type,id,c)})}catch(e){return res.json({streams:[]})}}const p=id.split(':'),tid=p[1],concert=id.startsWith('sktc:'),all=concert?await recent(c,300,CAT.CONCERTS,20):await recent(c,300,0),x=all.find(v=>v.id===tid);if(!x)return res.json({streams:[]});try{const td=await torrentData(x),vf=videoFiles(td.files),f=[...vf].sort((a,b)=>b.length-a.length)[0];if(!f)return res.json({streams:[]});return res.json({streams:[{name:`SKTorrent • ${is4k(x)?'4K/UHD':/1080p/i.test(x.name)?'1080p':'Video'}`,title:`${x.name}\n${x.size} • ${x.seeds} seed`,infoHash:td.hash,fileIdx:f.index,behaviorHints:{filename:f.path,bingeGroup:`skt-${tid}`}}]})}catch(e){return res.json({streams:[{name:'SKTorrent',title:e.message,externalUrl:x.detailUrl||BASE}]})}}

const app=express();app.set('trust proxy',1);app.use(cors());app.use(express.urlencoded({extended:true}));app.use(express.json());
app.get('/health',(_q,r)=>r.json({ok:true,addon:'SKTorrent Katalógy',version:'1.5.0',catalogs:ALL_CATS.length,search:true,concertSearch:true,standardIds:true,loginRequiredForCatalogs:false,userLoginConfigured:false,serverDownloadCredentials:Boolean(process.env.SKT_UID&&process.env.SKT_PASS),categories:CAT,at:new Date().toISOString()}));
app.get('/poster.svg',(q,r)=>r.type('svg').send(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900"><rect width="100%" height="100%" fill="#171717"/><text x="300" y="390" text-anchor="middle" fill="white" font-family="Arial" font-size="42" font-weight="700">SKTorrent</text><text x="300" y="450" text-anchor="middle" fill="#ddd" font-family="Arial" font-size="20">${esc(String(q.query.title||'').slice(0,42))}</text></svg>`));
app.get('/configure',(req,res)=>{const base=baseUrl(req);res.type('html').send(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{font:16px system-ui;background:#101114;color:#eee;max-width:720px;margin:35px auto;padding:18px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:6px 0 15px;border-radius:9px}input{background:#1b1d22;color:#fff;border:1px solid #444}button{font-weight:700}code{word-break:break-all}.ok{color:#9f9}</style><h1>SKTorrent Katalógy v1.5</h1><p class="ok">SKTorrent prihlásenie nie je potrebné pre katalógy ani metadata.</p><p>Pridané je vyhľadávanie filmov, seriálov a koncertov priamo cez SKTorrent. Koncerty sa hľadajú priamo v kategórii Hudební videa. TMDB key je voliteľný pre lepšie české názvy a popisy.</p><input id=t type=password placeholder="TMDB API key (voliteľné)"><input id=pg type=number min=1 max=20 value=8><button onclick="go()">Vytvoriť manifest</button><p id=o></p><script>function go(){let c={tmdbKey:t.value.trim(),pages:+pg.value||8},x=btoa(unescape(encodeURIComponent(JSON.stringify(c)))).split('+').join('-').split('/').join('_').replace(/=+$/,''),m='${base}/'+x+'/manifest.json';o.innerHTML='<a href="stremio://'+m.replace(/^https?:\\/\\//,'')+'">Inštalovať do Stremio</a><br><br><code>'+m+'</code>'}</script>`)});
app.get('/manifest.json',(_q,r)=>r.json(manifest()));app.get('/:token/manifest.json',(_q,r)=>r.json(manifest()));
for(const pre of ['', '/:token']){app.get(`${pre}/catalog/:type/:id.json`,async(q,r)=>{try{await catalog(q,r,pre?dec(q.params.token):{})}catch(e){log('catalog',e.message);r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/catalog/:type/:id/:extra.json`,async(q,r)=>{try{await catalog(q,r,pre?dec(q.params.token):{})}catch(e){log('catalog',e.message);r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/meta/:type/:id.json`,async(q,r)=>{try{await meta(q,r,pre?dec(q.params.token):{})}catch(e){r.status(502).json({meta:null,error:e.message})}});app.get(`${pre}/stream/:type/:id.json`,async(q,r)=>{try{await stream(q,r,pre?dec(q.params.token):{})}catch(e){r.status(502).json({streams:[],error:e.message})}})}
app.get('/debug/catalog/:type/:id',async(q,r)=>{try{const spec=CATS.find(x=>x.type===q.params.type&&x.id===q.params.id);if(!spec)return r.status(404).json({ok:false});const raw=filter(spec.id,await sourceForCatalog(spec.id,{})),sample=await mapLimit(raw.slice(0,12),5,x=>resolveMeta(q,x,spec.type,{},spec.id.includes('koncert')));r.json({ok:true,id:spec.id,raw:raw.length,sample:sample.map(m=>({id:m.id,name:m.name,poster:m.poster,releaseInfo:m.releaseInfo,genres:m.genres}))})}catch(e){r.status(502).json({ok:false,error:e.message})}});
app.get('/debug/search/:type/:query',async(q,r)=>{try{const mode=q.params.type,query=clean(q.params.query);let raw,type='movie',concert=false;if(mode==='concert'){concert=true;raw=await searchConcertItems(query,{},6)}else{type=mode==='series'?'series':'movie';raw=(await searchItems(query,{},4)).filter(type==='series'?isSeries:isMovie)}raw=raw.sort((a,b)=>searchRank(b,query)-searchRank(a,query));const sample=await mapLimit(raw.slice(0,10),5,x=>resolveMeta(q,x,type,{},concert));r.json({ok:true,type:concert?'concert':type,query,raw:raw.length,sample:sample.map(m=>({id:m.id,name:m.name,poster:m.poster,releaseInfo:m.releaseInfo}))})}catch(e){r.status(502).json({ok:false,error:e.message})}});
app.get('/debug/concert-match/:query',async(q,r)=>{try{const items=await searchConcertItems(q.params.query,{},2),sample=await mapLimit(items.slice(0,10),3,async x=>({source:x.name,year:x.year,meta:await resolveMeta(q,x,'movie',{},true)}));r.json({ok:true,count:items.length,sample})}catch(e){r.status(502).json({ok:false,error:e.message})}});
app.get('/',(_q,r)=>r.redirect('/configure'));
app.listen(PORT,()=>{log(`SKTorrent addon v1.5 listening on ${PORT}`);setTimeout(async()=>{try{const [d,s,u,k]=await Promise.all([fetchPage(0,{},CAT.DABING),fetchPage(0,{},CAT.SERIES),fetchPage(0,{},CAT.UHD),fetchPage(0,{},CAT.CONCERTS)]);log(`Category self-test dabing=${d.length} series=${s.length} uhd=${u.length} concerts=${k.length}`);const cure=k.find(x=>/the\s+cure/i.test(x.name));if(cure){const m=await resolveMeta({protocol:'https',get:()=> 'sktorrent-stremio-nuvio-addon.onrender.com'},cure,'movie',{},true);log(`Concert guard source=${cure.name} resolved=${m.name} id=${m.id} poster=${m.poster}`)}}catch(e){log('Category self-test failed',e.message)}},1500)});
