'use strict';
const express=require('express'),cors=require('cors'),axios=require('axios'),cheerio=require('cheerio'),bencode=require('bncode'),crypto=require('crypto');
const app=express(),PORT=Number(process.env.PORT||7000),BASE='https://sktorrent.eu',SEARCH=`${BASE}/torrent/torrents_v2.php`,TTL=Number(process.env.CACHE_TTL_SECONDS||600)*1000;
app.set('trust proxy',1);app.use(cors());app.use(express.urlencoded({extended:true}));app.use(express.json());
const cache=new Map();
const CATS=[
 ['movie','skt-novinky-dabing-filmy','🆕 SKT: Novinky CZ/SK dabing – filmy'],['series','skt-novinky-dabing-serialy','🆕 SKT: Novinky CZ/SK dabing – seriály'],['series','skt-serialy-czsk','🇨🇿🇸🇰 SKT: Seriály – CZ/SK dabing'],['movie','skt-4k-uhd-czsk','💎 SKT: 4K / UHD CZ/SK'],['movie','skt-filmove-novinky','🎬 SKT: Filmové novinky'],['movie','skt-posledne-filmy','🕒 SKT: Posledné pridané filmy'],['series','skt-posledne-serialy','🕒 SKT: Posledné pridané seriály'],['movie','skt-nove-koncerty','🎤 SKT: Nové koncerty'],['movie','skt-posledne-koncerty','🎶 SKT: Posledné pridané koncerty'],['movie','skt-4k-uhd-koncerty','✨ SKT: 4K / UHD koncerty']
].map(([type,id,name])=>({type,id,name}));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s||'').replace(/\s+/g,' ').trim(), nodiac=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const enc=o=>Buffer.from(JSON.stringify(o),'utf8').toString('base64url');
const dec=t=>{try{return t&&t!=='default'?JSON.parse(Buffer.from(t,'base64url').toString('utf8')):{}}catch{return{}}};
const client=c=>axios.create({timeout:12000,maxRedirects:5,headers:{'User-Agent':'Mozilla/5.0 Chrome/126 Safari/537.36','Accept-Language':'sk,cs;q=0.9,en;q=0.7',Referer:BASE+'/',...(c.uid&&c.pass?{Cookie:`uid=${c.uid}; pass=${c.pass}`}:{})}});
async function cached(k,fn){const h=cache.get(k);if(h&&h.exp>Date.now())return h.v;const v=await fn();cache.set(k,{v,exp:Date.now()+TTL});return v}
function dateFrom(t){const m=String(t).match(/Pridany\s+(\d{1,2})\/(\d{1,2})\/(\d{4})/i);return m?new Date(Date.UTC(+m[3],+m[2]-1,+m[1],12)):null}
function yearFrom(t){const a=[...String(t).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(x=>+x[1]),y=new Date().getUTCFullYear();return a.filter(v=>v<=y+1).pop()||null}
function abs(u){try{return new URL(u,SEARCH).href}catch{return null}}
function parseCell($,img){const a=$(img).closest('a'),td=a.closest('td'),href=a.attr('href')||'',m=href.match(/[?&]id=([^&]+)/);if(!m)return null;const txt=clean(td.text()),name=clean(a.attr('title')||$(img).attr('alt')||txt),cat=clean(td.find('b').first().text()),dm=dateFrom(txt);return{id:m[1],name:name.replace(/^Stiahni si\s*/i,''),category:cat,poster:abs($(img).attr('src')),size:(txt.match(/Velkost\s*([^|]+)/i)||[])[1]?.trim()||'?',seeds:+((txt.match(/Odosielaju\s*:\s*(\d+)/i)||[])[1]||0),addedDate:dm,added:dm?dm.toISOString().slice(0,10):null,year:yearFrom(name),downloadUrl:`${BASE}/torrent/download.php?id=${encodeURIComponent(m[1])}`}}
async function page(n,c){return cached(`p:${n}:${c.uid||'g'}`,async()=>{const r=await client(c).get(SEARCH,{params:{active:0,category:0,order:'data',by:'DESC',page:n}}),$=cheerio.load(r.data),out=[],seen=new Set();$('a[href^="details.php"] img').each((_,img)=>{const x=parseCell($,img);if(x&&!seen.has(x.id)){seen.add(x.id);out.push(x)}});return out})}
async function recent(c,need=160){const pages=Math.max(1,Math.min(20,Number(c.pages||8))),out=[],seen=new Set();for(let p=0;p<pages&&out.length<need;p++){let a=[];try{a=await page(p,c)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if(a.length<10)break}return out.sort((a,b)=>(b.addedDate?.getTime()||0)-(a.addedDate?.getTime()||0))}
const isSeries=x=>/seri[aá]l/i.test(x.category), is4k=x=>/\b(?:2160p|4k|uhd)\b|hdr10|dolby\s*vision/i.test(x.name);
function isMovie(x){const c=nodiac(x.category).toLowerCase();return !c.includes('serial')&&!c.includes('hudba')&&!c.includes('hudebni videa')&&(c.includes('film')||c.includes('uhd')||c.includes('blu-ray'))}
function isCzSk(x){const t=`${x.category} ${x.name}`;return /filmy\s+cz\s*\/\s*sk\s+dabing/i.test(x.category)||/(?:^|[\s(\[\/_-])(CZ|SK)(?=$|[\s)\]\/, _-])/i.test(t)||/CZ\s*\/\s*(SK|EN)|SK\s*\/\s*(CZ|EN)/i.test(t)}
function isConcert(x){const c=nodiac(x.category).toLowerCase(),n=x.name;if(c.includes('hudebni videa'))return true;if(!c.includes('hudba')||/\b(flac|mp3|wavpack|wav|aac|hi-?res)\b/i.test(n))return false;return /\b(concert|koncert|live\s+(at|in)|tour|festival|unplugged|živ[eě])\b/i.test(n)&&/\b(2160p|1080p|720p|4k|uhd|blu-?ray|web-?dl|webrip|x26[45]|mkv|mp4)\b/i.test(n)}
function fresh(x,d=120){return x.addedDate&&Date.now()-x.addedDate<d*864e5} function newRel(x){const y=new Date().getUTCFullYear();return x.year?x.year>=y-1:fresh(x)}
function filter(id,a){switch(id){case'skt-novinky-dabing-filmy':return a.filter(x=>isMovie(x)&&isCzSk(x)&&newRel(x));case'skt-novinky-dabing-serialy':return a.filter(x=>isSeries(x)&&isCzSk(x)&&newRel(x));case'skt-serialy-czsk':return a.filter(x=>isSeries(x)&&isCzSk(x));case'skt-4k-uhd-czsk':return a.filter(x=>isMovie(x)&&isCzSk(x)&&is4k(x));case'skt-filmove-novinky':return a.filter(x=>isMovie(x)&&newRel(x));case'skt-posledne-filmy':return a.filter(isMovie);case'skt-posledne-serialy':return a.filter(isSeries);case'skt-nove-koncerty':return a.filter(x=>isConcert(x)&&newRel(x));case'skt-posledne-koncerty':return a.filter(isConcert);case'skt-4k-uhd-koncerty':return a.filter(x=>isConcert(x)&&is4k(x));default:return[]}}
function lookupTitle(n){return clean(n.replace(/\[[^\]]*\]/g,' ').replace(/\((?:CZ|SK|EN|CZ\/SK|SK\/CZ|CZ\/EN|SK\/EN)[^)]*\)/gi,' ').replace(/\bS\d{1,2}(?:E\d{1,3})?\b/gi,' ').replace(/\b(2160p|1080p|720p|4k|uhd|hdr|hevc|x265|x264|web-?dl|webrip|bluray|bdrip|remux)\b/gi,' ')).split(/\s+\/\s+/)[0]}
function seriesKey(n){return nodiac(lookupTitle(n)).toLowerCase().replace(/\b\d+\.?\s*(serie|seria|series|season)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function episode(n){const s=nodiac(n);let m=s.match(/\bS(\d{1,2})[ ._-]*E(\d{1,3})\b/i);if(m)return{season:+m[1],episode:+m[2]};m=s.match(/\b(\d{1,2})x(\d{1,3})\b/i);return m?{season:+m[1],episode:+m[2]}:{season:null,episode:null}}
function groups(a){const m=new Map();for(const x of a){const k=seriesKey(x.name);if(!k)continue;if(!m.has(k))m.set(k,{key:k,name:lookupTitle(x.name)||x.name,poster:x.poster,items:[]});m.get(k).items.push(x)}return[...m.values()]}
function poster(req,x){return x.poster||`${req.protocol}://${req.get('host')}/poster.svg?title=${encodeURIComponent(x.name||'SKTorrent')}`}
function movieMeta(req,x,concert=false){return{id:`${concert?'sktc':'skt'}:${x.id}`,type:'movie',name:x.name,poster:poster(req,x),description:`${x.category}${x.size?' • '+x.size:''}${x.seeds!=null?' • '+x.seeds+' seed':''}`,releaseInfo:x.year?String(x.year):x.added||undefined,genres:concert?['Concert']:undefined,behaviorHints:{defaultVideoId:`${concert?'sktc':'skt'}:${x.id}`}}}
function groupMeta(req,g){const x=g.items[0];return{id:`sktseries:${Buffer.from(g.key).toString('base64url')}`,type:'series',name:g.name,poster:poster(req,{...x,name:g.name}),description:`SKTorrent • ${g.items.length} torrentov`,releaseInfo:x.year?String(x.year):x.added||undefined}}
async function torrentData(x,c){return cached(`t:${x.id}:${c.uid||'g'}`,async()=>{const r=await client(c).get(x.downloadUrl,{responseType:'arraybuffer'}),buf=Buffer.from(r.data);if(buf.slice(0,80).toString().match(/<html|<!doctype/i))throw new Error('SKTorrent vrátil HTML namiesto .torrent – skontroluj uid/pass.');const t=bencode.decode(buf),info=bencode.encode(t.info),hash=crypto.createHash('sha1').update(info).digest('hex'),files=t.info.files?t.info.files.map((f,i)=>({index:i,path:(f['path.utf-8']||f.path||[]).map(p=>Buffer.from(p).toString()).join('/'),length:Number(f.length||0)})):[{index:0,path:Buffer.from(t.info['name.utf-8']||t.info.name||'video').toString(),length:Number(t.info.length||0)}];return{hash,files}})}
const videoFiles=a=>a.filter(f=>/\.(mkv|mp4|avi|m4v|ts|m2ts|webm)$/i.test(f.path));
async function seriesVideos(g,c){
  const vids=[],seen=new Set();
  for(const x of g.items.slice(0,25)){
    const e=episode(x.name);
    if(e.season&&e.episode){
      const k=`${e.season}:${e.episode}`;
      if(!seen.has(k)){seen.add(k);vids.push({id:`sktv:${x.id}:${e.season}:${e.episode}`,title:`S${String(e.season).padStart(2,'0')}E${String(e.episode).padStart(2,'0')}`,season:e.season,episode:e.episode,released:x.addedDate?.toISOString()})}
      continue;
    }
    if(c.uid&&c.pass){
      try{
        const td=await torrentData(x,c);
        for(const f of videoFiles(td.files)){
          const pe=episode(f.path);
          if(pe.season&&pe.episode){
            const k=`${pe.season}:${pe.episode}`;
            if(!seen.has(k)){seen.add(k);vids.push({id:`sktf:${x.id}:${f.index}:${pe.season}:${pe.episode}`,title:`S${String(pe.season).padStart(2,'0')}E${String(pe.episode).padStart(2,'0')}`,season:pe.season,episode:pe.episode,released:x.addedDate?.toISOString()})}
          }
        }
      }catch{}
    }
  }
  return vids.sort((a,b)=>a.season-b.season||a.episode-b.episode);
}
async function enrich(meta,x,type,c){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return meta;try{const q=lookupTitle(x.name),path=type==='series'?'tv':'movie',r=await axios.get(`https://api.themoviedb.org/3/search/${path}`,{params:{api_key:key,query:q,language:'cs-CZ',...(x.year?{year:x.year,first_air_date_year:x.year}:{})},timeout:6000}),z=r.data.results?.[0];if(!z)return meta;const name=z.title||z.name||meta.name;return{...meta,name,poster:z.poster_path?`https://image.tmdb.org/t/p/w500${z.poster_path}`:meta.poster,background:z.backdrop_path?`https://image.tmdb.org/t/p/original${z.backdrop_path}`:undefined,description:z.overview||meta.description,releaseInfo:(z.release_date||z.first_air_date||'').slice(0,4)||meta.releaseInfo}}catch{return meta}}
function manifest(){return{id:'community.sktorrent.catalogs',version:'1.0.0',name:'SKTorrent Katalógy',description:'CZ/SK filmy, seriály, 4K/UHD a koncerty zo SKTorrentu.',resources:[{name:'catalog',types:['movie','series']},{name:'meta',types:['movie','series'],idPrefixes:['skt:','sktc:','sktseries:']},{name:'stream',types:['movie','series'],idPrefixes:['skt:','sktc:','sktv:','sktf:']}],types:['movie','series'],catalogs:CATS.map(c=>({...c,extra:[{name:'skip',isRequired:false}]})),idPrefixes:['skt:','sktc:','sktseries:','sktv:','sktf:'],behaviorHints:{configurable:true,configurationRequired:false}}}
const cfg=req=>dec(req.params.token), skipOf=s=>Math.max(0,+((String(s||'').match(/skip=(\d+)/)||[])[1]||0));
async function catalog(req,res,c){const spec=CATS.find(x=>x.type===req.params.type&&x.id===req.params.id);if(!spec)return res.status(404).json({metas:[]});const sk=skipOf(req.params.extra),a=filter(spec.id,await recent(c,sk+120));return res.json({metas:(spec.type==='series'?groups(a).map(g=>groupMeta(req,g)):a.map(x=>movieMeta(req,x,spec.id.includes('koncert')))).slice(sk,sk+40)})}
async function meta(req,res,c){const{id,type}=req.params;if(type==='movie'&&(id.startsWith('skt:')||id.startsWith('sktc:'))){const tid=id.split(':')[1],x=(await recent(c,220)).find(v=>v.id===tid);if(!x)return res.json({meta:null});return res.json({meta:await enrich(movieMeta(req,x,id.startsWith('sktc:')),x,'movie',c)})}if(type==='series'&&id.startsWith('sktseries:')){let k='';try{k=Buffer.from(id.slice(10),'base64url').toString()}catch{}const g=groups(await recent(c,240)).find(z=>z.key===k);if(!g)return res.json({meta:null});let m={...groupMeta(req,g),videos:await seriesVideos(g,c)};m=await enrich(m,g.items[0],'series',c);return res.json({meta:m})}res.json({meta:null})}
async function stream(req,res,c){if(!c.uid||!c.pass)return res.json({streams:[{name:'SKTorrent – konfigurácia',title:'Nastav uid/pass cez /configure.',externalUrl:`${req.protocol}://${req.get('host')}/configure`} ]});const p=req.params.id.split(':'),kind=p[0],tid=p[1],a=await recent(c,240),x=a.find(v=>v.id===tid);if(!x)return res.json({streams:[]});try{const td=await torrentData(x,c);let file;if(kind==='sktf')file=td.files.find(f=>f.index===+p[2]);else{const s=kind==='sktv'?+p[2]:null,e=kind==='sktv'?+p[3]:null;const vf=videoFiles(td.files);file=(s&&e?vf.find(f=>{const q=episode(f.path);return q.season===s&&q.episode===e}):null)||vf.sort((a,b)=>b.length-a.length)[0]}if(!file)return res.json({streams:[]});res.json({streams:[{name:`SKTorrent • ${is4k(x)?'4K/UHD':/1080p/i.test(x.name)?'1080p':'Video'}`,title:`${x.name}\n${x.size} • ${x.seeds} seed`,infoHash:td.hash,fileIdx:file.index,behaviorHints:{filename:file.path,bingeGroup:`skt-${tid}`}}]})}catch(e){res.json({streams:[{name:'SKTorrent – chyba',title:e.message,externalUrl:`${req.protocol}://${req.get('host')}/configure`} ]})}}
app.get('/health',(_q,r)=>r.json({ok:true,addon:'SKTorrent Katalógy',version:'1.0.0',catalogs:CATS.length,at:new Date().toISOString()}));
app.get('/poster.svg',(q,r)=>{r.type('svg').send(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900"><rect width="100%" height="100%" fill="#171717"/><text x="300" y="390" text-anchor="middle" fill="white" font-family="Arial" font-size="42" font-weight="700">SKTorrent</text><text x="300" y="450" text-anchor="middle" fill="#ddd" font-family="Arial" font-size="20">${esc(String(q.query.title||'').slice(0,42))}</text></svg>`) });
app.get('/configure',(req,res)=>{const base=(process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');res.type('html').send(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{font:16px system-ui;background:#101114;color:#eee;max-width:720px;margin:35px auto;padding:18px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:6px 0 15px;border-radius:9px}input{background:#1b1d22;color:#fff;border:1px solid #444}button{font-weight:700}code{word-break:break-all}</style><h1>SKTorrent Katalógy</h1><p>Zadaj cookie hodnoty uid/pass zo svojho SKTorrent účtu. TMDB key je voliteľný.</p><input id=u placeholder="uid"><input id=p type=password placeholder="pass"><input id=t type=password placeholder="TMDB API key"><input id=pg type=number min=1 max=20 value=8><button onclick="go()">Vytvoriť manifest</button><p id=o></p><script>function go(){let c={uid:u.value.trim(),pass:p.value.trim(),tmdbKey:t.value.trim(),pages:+pg.value||8},x=btoa(unescape(encodeURIComponent(JSON.stringify(c)))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,''),m='${base}/'+x+'/manifest.json';o.innerHTML='<a href="stremio://'+m.replace(/^https?:\\/\\//,'')+'">Inštalovať do Stremio</a><br><br><code>'+m+'</code>'}</script>`) });
app.get('/manifest.json',(_q,r)=>r.json(manifest()));app.get('/:token/manifest.json',(_q,r)=>r.json(manifest()));
for(const pre of ['', '/:token']){app.get(`${pre}/catalog/:type/:id.json`,async(q,r)=>{try{await catalog(q,r,pre?cfg(q):{})}catch(e){r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/catalog/:type/:id/:extra.json`,async(q,r)=>{try{await catalog(q,r,pre?cfg(q):{})}catch(e){r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/meta/:type/:id.json`,async(q,r)=>{try{await meta(q,r,pre?cfg(q):{})}catch(e){r.status(502).json({meta:null,error:e.message})}});app.get(`${pre}/stream/:type/:id.json`,async(q,r)=>{try{await stream(q,r,pre?cfg(q):{})}catch(e){r.status(502).json({streams:[],error:e.message})}})}
app.get('/',(_q,r)=>r.redirect('/configure'));app.listen(PORT,()=>console.log(`SKTorrent addon listening on ${PORT}`));
