
// v1.7: encrypted username/password configuration + automatic SKTorrent login
const LOGIN_TTL=30*60*1000;
function cfgSecret(){const s=String(process.env.CONFIG_SECRET||'');if(!s)throw Error('CONFIG_SECRET is not configured');return crypto.createHash('sha256').update(s).digest()}
function sealLogin(v){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',cfgSecret(),iv),plain=Buffer.from(JSON.stringify(v),'utf8'),ct=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag();return [iv,tag,ct].map(x=>x.toString('base64url')).join('.')}
function openLogin(s){const [a,b,c]=String(s||'').split('.');if(!a||!b||!c)throw Error('Invalid secure config');const d=crypto.createDecipheriv('aes-256-gcm',cfgSecret(),Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString('utf8'))}
function authConfig(c={}){if(!c?.s)return c;try{return{...c,...openLogin(c.s)}}catch(e){log('secure config',e.message);return c}}
function authFingerprint(c={}){const a=authConfig(c);return crypto.createHash('sha256').update(`${a.sktUser||''}\0${a.sktPass||''}`).digest('hex').slice(0,24)}
function baseHeaders(referer=BASE+'/'){return{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36','Accept-Language':'sk,cs;q=0.9,en;q=0.7',Referer:referer}}
function mergeCookies(current,setCookies){const jar=new Map();for(const raw of String(current||'').split(';')){const p=raw.trim(),i=p.indexOf('=');if(i>0)jar.set(p.slice(0,i),p.slice(i+1))}for(const line of(setCookies||[])){const p=String(line).split(';',1)[0],i=p.indexOf('=');if(i>0)jar.set(p.slice(0,i),p.slice(i+1))}return[...jar].map(([k,v])=>`${k}=${v}`).join('; ')}
async function sktLoginCookie(c={},force=false){const a=authConfig(c),user=clean(a.sktUser),pass=String(a.sktPass||'');if(!user||!pass)return null;const key=`skt-login:${authFingerprint(a)}`,old=cache.get(key);if(!force&&old&&old.e>Date.now())return old.v;
 const loginUrl=`${BASE}/torrent/login.php`;
 try{
  const first=await axios.get(loginUrl,{timeout:12000,maxRedirects:5,httpAgent,httpsAgent,headers:baseHeaders(BASE+'/torrent/')});
  let cookie=mergeCookies('',first.headers['set-cookie']);
  const $=cheerio.load(first.data||''),form=$('form[action^="login.php?returnto=index.php"]').first().length?$('form[action^="login.php?returnto=index.php"]').first():$('form').filter((_,f)=>$(f).find('input[name="uid"]').length&&$(f).find('input[name="pwd"]').length).first();
  const action=form.length?form.attr('action'):'login.php?returnto=index.php',postUrl=new URL(action||'login.php?returnto=index.php',loginUrl).href,fields={};
  if(form.length)form.find('input[name]').each((_,el)=>{const n=$(el).attr('name');if(n)fields[n]=$(el).attr('value')||''});
  fields.uid=user;fields.pwd=pass;
  const post=await axios.post(postUrl,new URLSearchParams(fields).toString(),{timeout:12000,maxRedirects:0,httpAgent,httpsAgent,validateStatus:s=>s>=200&&s<400,headers:{...baseHeaders(loginUrl),'Content-Type':'application/x-www-form-urlencoded',Origin:BASE,...(cookie?{Cookie:cookie}:{})}});
  cookie=mergeCookies(cookie,post.headers['set-cookie']);
  const postText=String(post.data||'');
  if(/incorrect|nespr[aá]vn|wrong password|login failed/i.test(postText))throw Error('SKTorrent odmietol používateľské meno alebo heslo.');
  const verify=await axios.get(`${BASE}/torrent/index.php`,{timeout:12000,maxRedirects:5,httpAgent,httpsAgent,headers:{...baseHeaders(postUrl),...(cookie?{Cookie:cookie}:{})}}),html=String(verify.data||'');
  cookie=mergeCookies(cookie,verify.headers['set-cookie']);
  if(!/href=["'][^"']*usercp\.php/i.test(html)&&!/logout\.php/i.test(html))throw Error('SKTorrent prihlásenie sa nepotvrdilo. Skontroluj meno a heslo.');
  cache.set(key,{v:cookie,e:Date.now()+LOGIN_TTL});log('SKTorrent username/password login ok');return cookie
 }catch(e){cache.delete(key);throw Error(`SKTorrent login zlyhal: ${e.message}`)}
}
async function configuredCookie(c={},force=false){const a=authConfig(c);if(a.sktUser&&a.sktPass)return sktLoginCookie(a,force);return null}
async function downloadWithCookie(x,cookie,mode){const r=await axios.get(x.downloadUrl,{responseType:'arraybuffer',timeout:15000,maxRedirects:5,httpAgent,httpsAgent,validateStatus:s=>s>=200&&s<400,headers:{...baseHeaders(x.detailUrl||SEARCH),...(cookie?{Cookie:cookie}:{})}}),buf=Buffer.from(r.data);if(!looksLikeTorrent(buf))throw Error(`${mode}: SKTorrent vrátil HTML alebo neplatný .torrent`);return{buf,mode}}
async function downloadTorrentBuffer(x,c={}){let last='';
 try{return await downloadWithCookie(x,null,'guest')}catch(e){last=e.message}
 const a=authConfig(c);
 if(a.sktUser&&a.sktPass){
  try{return await downloadWithCookie(x,await configuredCookie(a,false),'user-login')}catch(e){last=e.message}
  try{return await downloadWithCookie(x,await configuredCookie(a,true),'user-relogin')}catch(e){last=e.message}
 }
 const envCookie=cookieHeader();if(envCookie)try{return await downloadWithCookie(x,envCookie,'server-auth')}catch(e){last=e.message}
 if(a.sktUser&&a.sktPass)throw Error(`SKTorrent prihlásenie/download zlyhal (${last}).`);
 throw Error(envCookie?`SKTorrent .torrent sa nepodarilo stiahnuť (${last}).`:'SKTorrent prehrávanie vyžaduje prihlásenie. Otvor konfigurátor a zadaj SKTorrent meno a heslo.')
}
async function torrentData(x,c={}){return cached(`tor:${x.id}`,864e5,async()=>{const{buf,mode}=await downloadTorrentBuffer(x,c),t=bencode.decode(buf);if(!t?.info)throw Error('Neplatný .torrent bez info sekcie.');const hash=crypto.createHash('sha1').update(bencode.encode(t.info)).digest('hex'),files=t.info.files?t.info.files.map((f,i)=>({index:i,path:(f['path.utf-8']||f.path||[]).map(p=>Buffer.from(p).toString()).join('/'),length:Number(f.length||0)})):[{index:0,path:Buffer.from(t.info['name.utf-8']||t.info.name||'video').toString(),length:Number(t.info.length||0)}];return{hash,files,mode}})}
async function streamsForStandard(type,id,c){c=authConfig(c);const bits=id.split(':'),base=/^tt\d+$/.test(bits[0])?bits[0]:(id.startsWith('tmdb:')?bits.slice(0,2).join(':'):id),season=/^tt\d+$/.test(bits[0])&&bits.length>=3?+bits[1]:null,ep=/^tt\d+$/.test(bits[0])&&bits.length>=3?+bits[2]:null,target=await targetFromStandard(type,base,c);if(!target)return[];const qs=[target.name,target.originalName,target.name&&String(target.name).split(':')[0]].filter(Boolean),all=[];for(const q of[...new Set(qs)]){try{all.push(...await searchItems(q,c,4))}catch{}}let ranked=[...new Map(all.map(x=>[x.id,x])).values()].map(x=>({x,s:scoreCandidate(x,target,type,season,ep),kind:'normal'})).filter(z=>z.s>=55);if(type==='movie')ranked.push(...await concertCandidatesForStandard(target,base,c));ranked=[...new Map(ranked.sort((a,b)=>b.s-a.s).map(z=>[z.x.id,z])).values()].slice(0,10);const streams=[];for(const z of ranked.slice(0,5)){try{const td=await torrentData(z.x,c),f=chooseVideoFile(td,type,season,ep);if(f)streams.push(makeStream(z.x,td,f,base))}catch(e){log(`torrent ${z.kind}`,z.x.name,e.message)}}return streams}
async function stream(req,res,c){c=authConfig(c);const{id,type}=req.params;if(/^tt\d+/.test(id)||id.startsWith('tmdb:')){try{return res.json({streams:await streamsForStandard(type,id,c)})}catch(e){log('standard stream',id,e.message);return res.json({streams:[]})}}const p=id.split(':'),tid=p[1],concert=id.startsWith('sktc:'),all=concert?await recent(c,300,CAT.CONCERTS,20):await recent(c,300,0),x=all.find(v=>v.id===tid);if(!x)return res.json({streams:[]});try{const td=await torrentData(x,c),f=chooseVideoFile(td,type);if(!f)return res.json({streams:[]});return res.json({streams:[makeStream(x,td,f,tid)]})}catch(e){return res.json({streams:[{name:'SKTorrent',title:e.message,externalUrl:x.detailUrl||BASE}]})}}
function manifest(){return{id:'community.sktorrent.catalogs',version:'1.7.0',name:'SKTorrent Katalógy',description:'SKTorrent katalógy s automatickým prihlásením cez meno/heslo, hybridnými IMDb/TMDB koncertmi a vlastným prehrávaním.',resources:[{name:'catalog',types:['movie','series']},{name:'meta',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:']},{name:'stream',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:']}],types:['movie','series'],catalogs:ALL_CATS.map(c=>({...c,search:undefined,concert:undefined,extra:c.search?[{name:'search',isRequired:true},{name:'skip',isRequired:false}]:[{name:'skip',isRequired:false}]})),idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:'],behaviorHints:{configurable:true,configurationRequired:false}}}
function removeRoute(path,method='get'){if(!app?._router?.stack)return;app._router.stack=app._router.stack.filter(l=>!(l.route?.path===path&&l.route?.methods?.[method]))}
removeRoute('/configure','get');removeRoute('/health','get');
app.get('/health',(_q,r)=>r.json({ok:true,addon:'SKTorrent Katalógy',version:'1.7.0',catalogs:ALL_CATS.length,search:true,concertSearch:true,hybridConcertIds:true,sktPlayback:true,standardIds:true,usernamePasswordLogin:true,encryptedLoginToken:true,configSecretConfigured:Boolean(process.env.CONFIG_SECRET),serverDownloadCredentials:Boolean(process.env.SKT_UID&&process.env.SKT_PASS),categories:CAT,at:new Date().toISOString()}));
app.post('/api/config',async(req,res)=>{try{if(!process.env.CONFIG_SECRET)return res.status(503).json({ok:false,error:'Server nemá CONFIG_SECRET.'});const sktUser=clean(req.body?.sktUser),sktPass=String(req.body?.sktPass||''),tmdbKey=clean(req.body?.tmdbKey),pg=Math.max(1,Math.min(20,Number(req.body?.pages||8)||8));if(!sktUser||!sktPass)return res.status(400).json({ok:false,error:'Zadaj SKTorrent meno aj heslo.'});const c={sktUser,sktPass};await sktLoginCookie(c,true);const wrapper={s:sealLogin(c),pages:pg,...(tmdbKey?{tmdbKey}:{})},token=Buffer.from(JSON.stringify(wrapper)).toString('base64url'),manifestUrl=`${baseUrl(req)}/${token}/manifest.json`;res.json({ok:true,token,manifest:manifestUrl,install:`stremio://${manifestUrl.replace(/^https?:\/\//,'')}`})}catch(e){res.status(401).json({ok:false,error:e.message})}});
app.get('/:token/debug/auth',async(req,res)=>{try{const c=authConfig(dec(req.params.token));if(!c.sktUser||!c.sktPass)return res.json({ok:false,error:'V konfigurácii nie je SKTorrent meno/heslo.'});await sktLoginCookie(c,true);res.json({ok:true,login:true})}catch(e){res.status(401).json({ok:false,error:e.message})}});
app.get('/configure',(req,res)=>{const base=baseUrl(req);res.type('html').send(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px system-ui;background:#101114;color:#eee;max-width:720px;margin:30px auto;padding:18px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:6px 0 14px;border-radius:9px}input{background:#1b1d22;color:#fff;border:1px solid #444}button{font-weight:700}.ok{color:#9f9}.err{color:#ff9b9b}code{word-break:break-all}small{color:#aaa}</style><h1>SKTorrent Katalógy v1.7</h1><p>Prihlásenie sa vykoná automaticky na SKTorrent.eu. Už nemusíš hľadať cookies <code>uid</code>/<code>pass</code>.</p><input id=u autocomplete="username" placeholder="SKTorrent používateľské meno"><input id=p type=password autocomplete="current-password" placeholder="SKTorrent heslo"><input id=t type=password placeholder="TMDB API key (voliteľné)"><input id=pg type=number min=1 max=20 value=8><button id=b onclick="go()">Overiť prihlásenie a vytvoriť manifest</button><p id=o></p><small>Heslo sa neposiela do URL v čitateľnej podobe. Server ho uloží iba do šifrovaného konfiguračného tokenu. Inštalačný/manifest odkaz nezdieľaj s inými ľuďmi.</small><script>async function go(){b.disabled=true;o.className='';o.textContent='Overujem SKTorrent prihlásenie…';try{let r=await fetch('${base}/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sktUser:u.value.trim(),sktPass:p.value,tmdbKey:t.value.trim(),pages:+pg.value||8})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Konfigurácia zlyhala');o.className='ok';o.innerHTML='✅ Prihlásenie funguje.<br><br><a href="'+j.install+'">Inštalovať do Stremio</a><br><br><code>'+j.manifest+'</code>'}catch(e){o.className='err';o.textContent='❌ '+e.message}finally{b.disabled=false}}</script>`)});
