 }
 const cine=await findCinemeta(x,type);if(cine){meta={...meta,...cine,id:cine.id||meta.id,type,poster:cine.poster||meta.poster,background:cine.background||meta.background,description:cine.description||meta.description,releaseInfo:cine.releaseInfo||meta.releaseInfo};if(type==='movie')meta.behaviorHints={...(cine.behaviorHints||{}),defaultVideoId:meta.id}}
 const t=await tmdbSearch(x,type,c,false);if(t){const date=t.release_date||t.first_air_date;meta={...meta,id:t.imdb||meta.id,name:t.title||t.name||meta.name,poster:t.poster_path?`https://image.tmdb.org/t/p/w500${t.poster_path}`:meta.poster,background:t.backdrop_path?`https://image.tmdb.org/t/p/original${t.backdrop_path}`:meta.background,description:t.overview||meta.description,releaseInfo:date?.slice(0,4)||meta.releaseInfo,imdbRating:t.vote_average?Number(t.vote_average).toFixed(1):meta.imdbRating};if(type==='movie')meta.behaviorHints={...(meta.behaviorHints||{}),defaultVideoId:meta.id}}
 return meta}
async function mapLimit(a,n,fn){const out=new Array(a.length);let i=0;async function w(){for(;;){const j=i++;if(j>=a.length)return;try{out[j]=await fn(a[j],j)}catch(e){log('mapLimit',e.message);out[j]=null}}}await Promise.all(Array.from({length:Math.min(n,Math.max(1,a.length))},w));return out.filter(Boolean)}
function dedupMetas(a){const m=new Map();for(const x of a){const k=x.id||`${x.type}:${nm(x.name)}:${x.releaseInfo||''}`;if(!m.has(k))m.set(k,x)}return [...m.values()]}
async function searchConcertItems(q,c={},maxPages=6){const out=[],seen=new Set();for(let p=0;p<maxPages;p++){let a=[];try{a=await fetchPage(p,c,CAT.CONCERTS,q)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if(a.length<10)break}return out.filter(isConcert)}
const SEARCH_CATS=[
 {type:'movie',id:'skt-search-filmy',name:'🔎 SKT: Hľadať filmy',search:true},
 {type:'series',id:'skt-search-serialy',name:'🔎 SKT: Hľadať seriály',search:true},
 {type:'movie',id:'skt-search-koncerty',name:'🔎 SKT: Hľadať koncerty',search:true,concert:true}
];
const ALL_CATS=[...CATS,...SEARCH_CATS];
function manifest(){return{id:'community.sktorrent.catalogs',version:'1.6.0',name:'SKTorrent Katalógy',description:'SKTorrent katalógy s hybridnými IMDb/TMDB koncertmi, vyhľadávaním a vlastným SKTorrent prehrávaním.',resources:[{name:'catalog',types:['movie','series']},{name:'meta',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:']},{name:'stream',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:']}],types:['movie','series'],catalogs:ALL_CATS.map(c=>({...c,search:undefined,concert:undefined,extra:c.search?[{name:'search',isRequired:true},{name:'skip',isRequired:false}]:[{name:'skip',isRequired:false}]})),idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:'],behaviorHints:{configurable:true,configurationRequired:false}}}
function extraOf(s){let raw=String(s||'');try{raw=decodeURIComponent(raw)}catch{}const p=new URLSearchParams(raw);return{skip:Math.max(0,Number(p.get('skip')||0)||0),search:clean(p.get('search')||'')}}
function searchRank(x,q){const a=nm(lookupTitle(x.name)),b=nm(q);if(!b)return 0;let s=0;if(a===b)s+=1000;else if(a.startsWith(b))s+=800;else if(a.includes(b))s+=650;for(const w of b.split(' ').filter(Boolean))if(a.includes(w))s+=60;if(x.year)s+=5;if(x.seeds)s+=Math.min(25,Math.log2(x.seeds+1)*4);return s}
async function catalog(req,res,c){const spec=ALL_CATS.find(x=>x.type===req.params.type&&x.id===req.params.id);if(!spec)return res.status(404).json({metas:[]});const ex=extraOf(req.params.extra),sk=ex.skip;
 if(spec.search){
   if(!ex.search)return res.json({metas:[]});
   let raw=spec.concert?await searchConcertItems(ex.search,c,Math.min(10,pages(c))):await searchItems(ex.search,c,Math.min(8,pages(c)));
   if(spec.concert)raw=raw.filter(isConcert);else raw=raw.filter(spec.type==='series'?isSeries:isMovie);
   raw=raw.sort((a,b)=>searchRank(b,ex.search)-searchRank(a,ex.search));
   const batch=raw.slice(sk,sk+60);let metas=await mapLimit(batch,7,x=>resolveMeta(req,x,spec.type,c,Boolean(spec.concert)));metas=dedupMetas(metas);if(spec.type==='series')metas=metas.filter(m=>/^tt\d+$/.test(m.id)||m.id.startsWith('tmdb:'));metas=metas.slice(0,PAGE_SIZE);
   log(`search ${spec.concert?'concert':spec.type} q=${ex.search} raw=${raw.length} metas=${metas.length}`);return res.json({metas});
 }
 const raw=filter(spec.id,await sourceForCatalog(spec.id,c)),concert=spec.id.includes('koncert'),batch=raw.slice(sk,sk+Math.max(PAGE_SIZE*2,60));let metas=await mapLimit(batch,7,x=>resolveMeta(req,x,spec.type,c,concert));metas=dedupMetas(metas).slice(0,PAGE_SIZE);log(`catalog ${spec.id} raw=${raw.length} batch=${batch.length} metas=${metas.length} standard=${metas.filter(m=>/^tt\d+$/.test(m.id)||m.id.startsWith('tmdb:')).length} concertsLocal=${metas.filter(m=>m.id.startsWith('sktc:')).length}`);res.json({metas})}
async function cinemetaMeta(type,id){try{const r=await axios.get(`https://v3-cinemeta.strem.io/meta/${type}/${id}.json`,{timeout:6000});return r.data?.meta||null}catch{return null}}
async function tmdbMeta(type,id,c){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return null;const n=Number(String(id).replace(/^tmdb:/,''));if(!n)return null;try{const t=type==='series'?'tv':'movie',r=await axios.get(`https://api.themoviedb.org/3/${t}/${n}`,{timeout:5000,params:{api_key:key,language:'cs-CZ'}}),z=r.data,date=z.release_date||z.first_air_date;return{id:`tmdb:${n}`,type,name:z.title||z.name,poster:z.poster_path?`https://image.tmdb.org/t/p/w500${z.poster_path}`:undefined,background:z.backdrop_path?`https://image.tmdb.org/t/p/original${z.backdrop_path}`:undefined,description:z.overview,releaseInfo:date?.slice(0,4)}}catch{return null}}
async function meta(req,res,c){const{id,type}=req.params;if(/^tt\d+$/.test(id)){const m=await cinemetaMeta(type,id);return res.json({meta:m})}if(id.startsWith('tmdb:'))return res.json({meta:await tmdbMeta(type,id,c)});if(type==='movie'&&(id.startsWith('skt:')||id.startsWith('sktc:'))){const tid=id.split(':')[1],all=id.startsWith('sktc:')?await recent(c,300,CAT.CONCERTS,20):await recent(c,300,0),x=all.find(v=>v.id===tid);return res.json({meta:x?await resolveMeta(req,x,'movie',c,id.startsWith('sktc:')):null})}res.json({meta:null})}

function looksLikeTorrent(buf){if(!buf||buf.length<20)return false;const head=buf.slice(0,180).toString('utf8').toLowerCase();return buf[0]===0x64&&!head.includes('<html')&&!head.includes('<!doctype')}
async function downloadTorrentBuffer(x){const baseHeaders={'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36','Accept-Language':'sk,cs;q=0.9,en;q=0.7',Referer:BASE+'/'};const serverCookie=cookieHeader(),attempts=[{mode:'guest',cookie:null},...(serverCookie?[{mode:'server-auth',cookie:serverCookie}]:[])];let last='';for(const a of attempts){try{const r=await axios.get(x.downloadUrl,{responseType:'arraybuffer',timeout:15000,maxRedirects:5,httpAgent,httpsAgent,validateStatus:s=>s>=200&&s<400,headers:{...baseHeaders,...(a.cookie?{Cookie:a.cookie}:{})}}),buf=Buffer.from(r.data);if(looksLikeTorrent(buf))return{buf,mode:a.mode};last=`${a.mode}: SKTorrent vrátil HTML alebo neplatný .torrent`}catch(e){last=`${a.mode}: ${e.message}`}}throw Error(serverCookie?`SKTorrent .torrent sa nepodarilo stiahnuť (${last}).`:`SKTorrent vyžaduje oprávnenie na stiahnutie .torrent. Katalógy fungujú bez loginu; pre prehrávanie môže byť potrebné serverové SKT_UID/SKT_PASS.`)}
async function torrentData(x){return cached(`tor:${x.id}`,864e5,async()=>{const{buf,mode}=await downloadTorrentBuffer(x),t=bencode.decode(buf);if(!t?.info)throw Error('Neplatný .torrent bez info sekcie.');const hash=crypto.createHash('sha1').update(bencode.encode(t.info)).digest('hex'),files=t.info.files?t.info.files.map((f,i)=>({index:i,path:(f['path.utf-8']||f.path||[]).map(p=>Buffer.from(p).toString()).join('/'),length:Number(f.length||0)})):[{index:0,path:Buffer.from(t.info['name.utf-8']||t.info.name||'video').toString(),length:Number(t.info.length||0)}];return{hash,files,mode}})}
const videoFiles=a=>a.filter(f=>/\.(mkv|mp4|avi|m4v|ts|m2ts|mov|wmv|webm)$/i.test(f.path));
function episode(n){const s=nodiac(n);let m=s.match(/\bS(\d{1,2})[ ._-]*E(\d{1,3})\b/i);if(m)return{season:+m[1],episode:+m[2]};m=s.match(/\b(\d{1,2})x(\d{1,3})\b/i);return m?{season:+m[1],episode:+m[2]}:{season:null,episode:null}}
