 }
 const cine=await findCinemeta(x,type);if(cine){meta={...meta,...cine,id:cine.id||meta.id,type,poster:cine.poster||meta.poster,background:cine.background||meta.background,description:cine.description||meta.description,releaseInfo:cine.releaseInfo||meta.releaseInfo};if(type==='movie')meta.behaviorHints={...(cine.behaviorHints||{}),defaultVideoId:meta.id}}
 const t=await tmdbSearch(x,type,c,false);if(t){const date=t.release_date||t.first_air_date;meta={...meta,id:t.imdb||meta.id,name:t.title||t.name||meta.name,poster:t.poster_path?`https://image.tmdb.org/t/p/w500${t.poster_path}`:meta.poster,background:t.backdrop_path?`https://image.tmdb.org/t/p/original${t.backdrop_path}`:meta.background,description:t.overview||meta.description,releaseInfo:date?.slice(0,4)||meta.releaseInfo,imdbRating:t.vote_average?Number(t.vote_average).toFixed(1):meta.imdbRating};if(type==='movie')meta.behaviorHints={...(meta.behaviorHints||{}),defaultVideoId:meta.id}}
 return meta}
async function mapLimit(a,n,fn){const out=new Array(a.length);let i=0;async function w(){for(;;){const j=i++;if(j>=a.length)return;try{out[j]=await fn(a[j],j)}catch(e){log('mapLimit',e.message);out[j]=null}}}await Promise.all(Array.from({length:Math.min(n,Math.max(1,a.length))},w));return out.filter(Boolean)}
function dedupMetas(a){const m=new Map();for(const x of a){const k=x.id||`${x.type}:${nm(x.name)}:${x.releaseInfo||''}`;if(!m.has(k))m.set(k,x)}return [...m.values()]}
function manifest(){return{id:'community.sktorrent.catalogs',version:'1.3.0',name:'SKTorrent Katalógy',description:'SKTorrent katalógy bez povinného prihlásenia, s IMDb/TMDB metadátami a bezpečným párovaním koncertov.',resources:[{name:'catalog',types:['movie','series']},{name:'meta',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:']},{name:'stream',types:['movie','series'],idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:']}],types:['movie','series'],catalogs:CATS.map(c=>({...c,extra:[{name:'skip',isRequired:false}]})),idPrefixes:['tt','tmdb:','skt:','sktc:','sktseries:','sktv:','sktf:'],behaviorHints:{configurable:true,configurationRequired:false}}}
const skipOf=s=>Math.max(0,+((decodeURIComponent(String(s||'')).match(/skip=(\d+)/)||[])[1]||0));
async function catalog(req,res,c){const spec=CATS.find(x=>x.type===req.params.type&&x.id===req.params.id);if(!spec)return res.status(404).json({metas:[]});const sk=skipOf(req.params.extra),raw=filter(spec.id,await sourceForCatalog(spec.id,c)),concert=spec.id.includes('koncert'),batch=raw.slice(sk,sk+Math.max(PAGE_SIZE*2,60));let metas=await mapLimit(batch,7,x=>resolveMeta(req,x,spec.type,c,concert));metas=dedupMetas(metas).slice(0,PAGE_SIZE);log(`catalog ${spec.id} raw=${raw.length} batch=${batch.length} metas=${metas.length} standard=${metas.filter(m=>/^tt\d+$/.test(m.id)||m.id.startsWith('tmdb:')).length} concertsLocal=${metas.filter(m=>m.id.startsWith('sktc:')).length}`);res.json({metas})}
async function cinemetaMeta(type,id){try{const r=await axios.get(`https://v3-cinemeta.strem.io/meta/${type}/${id}.json`,{timeout:6000});return r.data?.meta||null}catch{return null}}
async function tmdbMeta(type,id,c){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return null;const n=Number(String(id).replace(/^tmdb:/,''));if(!n)return null;try{const t=type==='series'?'tv':'movie',r=await axios.get(`https://api.themoviedb.org/3/${t}/${n}`,{timeout:5000,params:{api_key:key,language:'cs-CZ'}}),z=r.data,date=z.release_date||z.first_air_date;return{id:`tmdb:${n}`,type,name:z.title||z.name,poster:z.poster_path?`https://image.tmdb.org/t/p/w500${z.poster_path}`:undefined,background:z.backdrop_path?`https://image.tmdb.org/t/p/original${z.backdrop_path}`:undefined,description:z.overview,releaseInfo:date?.slice(0,4)}}catch{return null}}
async function meta(req,res,c){const{id,type}=req.params;if(/^tt\d+$/.test(id)){const m=await cinemetaMeta(type,id);return res.json({meta:m})}if(id.startsWith('tmdb:'))return res.json({meta:await tmdbMeta(type,id,c)});if(type==='movie'&&(id.startsWith('skt:')||id.startsWith('sktc:'))){const tid=id.split(':')[1],all=id.startsWith('sktc:')?await recent(c,300,CAT.CONCERTS,20):await recent(c,300,0),x=all.find(v=>v.id===tid);return res.json({meta:x?await resolveMeta(req,x,'movie',c,id.startsWith('sktc:')):null})}res.json({meta:null})}

async function torrentData(x){return cached(`tor:${x.id}`,864e5,async()=>{const r=await client().get(x.downloadUrl,{responseType:'arraybuffer',timeout:15000,validateStatus:s=>s>=200&&s<400}),buf=Buffer.from(r.data);if(buf.slice(0,150).toString().match(/<html|<!doctype/i))throw Error('SKTorrent neposkytol .torrent bez oprávnenia na sťahovanie. Katalóg funguje bez prihlásenia.');const t=bencode.decode(buf),hash=crypto.createHash('sha1').update(bencode.encode(t.info)).digest('hex'),files=t.info.files?t.info.files.map((f,i)=>({index:i,path:(f['path.utf-8']||f.path||[]).map(p=>Buffer.from(p).toString()).join('/'),length:Number(f.length||0)})):[{index:0,path:Buffer.from(t.info['name.utf-8']||t.info.name||'video').toString(),length:Number(t.info.length||0)}];return{hash,files}})}
const videoFiles=a=>a.filter(f=>/\.(mkv|mp4|avi|m4v|ts|m2ts|mov|wmv|webm)$/i.test(f.path));
function episode(n){const s=nodiac(n);let m=s.match(/\bS(\d{1,2})[ ._-]*E(\d{1,3})\b/i);if(m)return{season:+m[1],episode:+m[2]};m=s.match(/\b(\d{1,2})x(\d{1,3})\b/i);return m?{season:+m[1],episode:+m[2]}:{season:null,episode:null}}
