async function recent(c={},wanted=120,category=0,maxPages=null){const out=[],seen=new Set(),limit=maxPages||pages(c);for(let p=0;p<limit;p++){let a=[];try{a=await fetchPage(p,c,category)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if(a.length<10)break;if(out.length>=Math.max(200,wanted*5)&&p>=2)break}return out.sort((a,b)=>(b.addedDate?.getTime()||0)-(a.addedDate?.getTime()||0))}
async function mergeSources(...arrs){const m=new Map();for(const arr of await Promise.all(arrs))for(const x of arr)if(!m.has(x.id))m.set(x.id,x);return [...m.values()].sort((a,b)=>(b.addedDate?.getTime()||0)-(a.addedDate?.getTime()||0))}
async function searchItems(q,c={},maxPages=4){const out=[],seen=new Set();for(let p=0;p<maxPages;p++){let a=[];try{a=await fetchPage(p,c,0,q)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if(a.length<10)break}return out}
const is4k=x=>/\b(2160p|4k|uhd)\b|hdr10\+?|dolby\s*vision|\bDV\b/i.test(x.name);
const isSeries=x=>/seri[aá]l/i.test(x.category);
function isMovie(x){const c=nodiac(x.category).toLowerCase();return !c.includes('serial')&&!c.includes('hudba')&&!c.includes('hudebni videa')&&!c.includes('tv porad')&&!c.includes('sport')&&(c.includes('film')||c.includes('uhd')||c.includes('blu-ray'))}
function isCzSk(x){const t=`${x.category} ${x.name}`;return /filmy\s+cz\s*\/\s*sk\s+dabing/i.test(x.category)||/(?:^|[\s(\[\/_-])(CZ|SK)(?=$|[\s)\]\/, _-])/i.test(t)||/CZ\s*\/\s*(SK|EN)|SK\s*\/\s*(CZ|EN)/i.test(t)}
function isConcert(x){const c=nodiac(x.category).toLowerCase();if(c.includes('hudebni videa'))return true;if(!c.includes('hudba')||/\b(flac|mp3|wavpack|wav|aac|hi-?res)\b/i.test(x.name))return false;return /\b(concert|koncert|live|tour|festival|unplugged|ziv[eě])\b/i.test(x.name)&&/\b(2160p|1080p|720p|4k|uhd|blu-?ray|web-?dl|webrip|x26[45]|mkv|mp4)\b/i.test(x.name)}
function isAllowedStreamCategory(x){const c=nodiac(x.category).toLowerCase();return /film|seri|tv porad|dokument|sport|hudebni videa/.test(c)}
const fresh=(x,d=120)=>x.addedDate&&Date.now()-x.addedDate.getTime()<d*864e5;
const newRel=x=>x.year?x.year>=new Date().getUTCFullYear()-1:fresh(x);
async function sourceForCatalog(id,c){switch(id){case'skt-novinky-dabing-filmy':return recent(c,160,CAT.DABING);case'skt-novinky-dabing-serialy':case'skt-serialy-czsk':case'skt-posledne-serialy':return recent(c,220,CAT.SERIES);case'skt-4k-uhd-czsk':return mergeSources(recent(c,160,CAT.UHD),recent(c,160,CAT.DABING));case'skt-nove-koncerty':case'skt-posledne-koncerty':return recent(c,180,CAT.CONCERTS);case'skt-4k-uhd-koncerty':return recent(c,300,CAT.CONCERTS,20);default:return recent(c,220,0)}}
function filter(id,a){switch(id){case'skt-novinky-dabing-filmy':return a.filter(x=>isMovie(x)&&isCzSk(x)&&newRel(x));case'skt-novinky-dabing-serialy':return a.filter(x=>isSeries(x)&&isCzSk(x)&&(fresh(x)||newRel(x)));case'skt-serialy-czsk':return a.filter(x=>isSeries(x)&&isCzSk(x));case'skt-4k-uhd-czsk':return a.filter(x=>isMovie(x)&&isCzSk(x)&&is4k(x));case'skt-filmove-novinky':return a.filter(x=>isMovie(x)&&newRel(x));case'skt-posledne-filmy':return a.filter(isMovie);case'skt-posledne-serialy':return a.filter(isSeries);case'skt-nove-koncerty':return a.filter(x=>isConcert(x)&&newRel(x));case'skt-posledne-koncerty':return a.filter(isConcert);case'skt-4k-uhd-koncerty':return a.filter(x=>isConcert(x)&&is4k(x));default:return[]}}

const nm=s=>nodiac(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
function hitYear(h){return +((String(h.releaseInfo||h.year||'').match(/\b(19\d{2}|20\d{2})\b/)||[])[1]||0)||null}
function pickHit(arr,q,y){const nq=nm(q);let best=null,score=-999;for(const h of arr||[]){const hn=nm(h.name||h.title);let s=hn===nq?100:(hn.includes(nq)||nq.includes(hn)?65:0);const hy=hitYear(h);if(y&&hy)s+=Math.abs(y-hy)<=1?25:-35;if(h.poster)s+=5;if(s>score){score=s;best=h}}return score>=55?best:null}
async function cinemetaSearch(type,q){return cached(`cine-search:${type}:${q.toLowerCase()}`,META_TTL,async()=>{try{const r=await axios.get(`https://v3-cinemeta.strem.io/catalog/${type==='series'?'series':'movie'}/top/search=${encodeURIComponent(q)}.json`,{timeout:5000});return r.data?.metas||[]}catch(e){log('Cinemeta search',q,e.message);return[]}})}
async function findCinemeta(x,type){for(const q of lookupCandidates(x.name)){const h=pickHit(await cinemetaSearch(type,q),q,x.year);if(h)return h}return null}
const CONCERT_MARKERS=['live','concert','koncert','festival','tour','unplugged','anniversary','pohoda','wembley','montreux','glastonbury','rockpalast','arena','stadium','budokan','curaetion'];
function wordSet(s){return new Set(nm(s).split(' ').filter(w=>w&&w.length>1&&!['the','and','of','at','in','a','an'].includes(w)&&!/^(19|20)\d{2}$/.test(w)))}
function concertMatchScore(source,cand){const sn=nm(source.name),cn=nm(cand.name||cand.title),sw=wordSet(source.name),cw=wordSet(cand.name||cand.title),shared=[...sw].filter(w=>cw.has(w)),ratio=sw.size?shared.length/sw.size:0;const sourceMarkers=CONCERT_MARKERS.filter(m=>sn.includes(m)),candMarkers=CONCERT_MARKERS.filter(m=>cn.includes(m));const hy=hitYear(cand);if(source.year&&hy&&Math.abs(source.year-hy)>1)return-999;if(sourceMarkers.length&&!sourceMarkers.some(m=>candMarkers.includes(m)))return-999;if(sw.size>=4&&shared.length<3)return-999;if(ratio<0.5)return-999;let s=Math.round(ratio*100)+shared.length*5+(sourceMarkers.some(m=>candMarkers.includes(m))?30:0);if(source.year&&hy&&Math.abs(source.year-hy)<=1)s+=25;if(cand.poster)s+=5;return s}
async function findConcertCinemeta(x){let best=null,bestScore=-999;for(const q of lookupCandidates(x.name)){for(const h of await cinemetaSearch('movie',q)){const s=concertMatchScore(x,h);if(s>bestScore){best=h;bestScore=s}}}return bestScore>=80?best:null}
async function tmdbSearch(x,type,c,concert=false){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return null;for(const q of lookupCandidates(x.name)){try{const t=type==='series'?'tv':'movie',yr=type==='series'?'first_air_date_year':'year',r=await axios.get(`https://api.themoviedb.org/3/search/${t}`,{timeout:5000,params:{api_key:key,query:q,language:'cs-CZ',include_adult:false,...(x.year?{[yr]:x.year}:{})}}),hits=r.data?.results||[];let h;if(concert){h=hits.map(z=>({z,s:concertMatchScore(x,{name:z.title||z.name,releaseInfo:z.release_date||z.first_air_date,poster:z.poster_path})})).filter(v=>v.s>=80).sort((a,b)=>b.s-a.s)[0]?.z}else h=hits[0];if(h){let imdb=null;try{const e=await axios.get(`https://api.themoviedb.org/3/${t}/${h.id}/external_ids`,{timeout:4000,params:{api_key:key}});imdb=e.data?.imdb_id||null}catch{}return{...h,imdb}}}catch(e){log('TMDB',q,e.message)}}return null}
function baseUrl(req){return String(process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'')}
const fallbackPoster=(req,t)=>`${baseUrl(req)}/poster.svg?title=${encodeURIComponent(t||'SKTorrent')}`;
function localMeta(req,x,type,concert=false){const id=type==='series'?`sktseries:${x.id}`:`${concert?'sktc':'skt'}:${x.id}`;return{id,type,name:displayTitle(x.name),poster:x.poster||fallbackPoster(req,x.name),posterShape:'poster',description:[concert?'Koncert':x.category,x.added&&`Pridané ${x.added}`,x.size,`${x.seeds} seed`].filter(Boolean).join(' • '),releaseInfo:x.year?String(x.year):x.added||undefined,genres:concert?['Concert','Music']:undefined,...(type==='movie'?{behaviorHints:{defaultVideoId:id}}:{})}}
async function resolveMeta(req,x,type,c,concert=false){let meta=localMeta(req,x,type,concert);
 if(concert){
   const cine=await findConcertCinemeta(x);if(cine)meta={...meta,poster:cine.poster||meta.poster,background:cine.background||meta.background,description:cine.description||meta.description,imdbRating:cine.imdbRating||meta.imdbRating};
   const t=await tmdbSearch(x,'movie',c,true);if(t)meta={...meta,poster:t.poster_path?`https://image.tmdb.org/t/p/w500${t.poster_path}`:meta.poster,background:t.backdrop_path?`https://image.tmdb.org/t/p/original${t.backdrop_path}`:meta.background,description:t.overview||meta.description,imdbRating:t.vote_average?Number(t.vote_average).toFixed(1):meta.imdbRating};
   return meta;
