'use strict';
const express=require('express');
const cors=require('cors');
const axios=require('axios');
const cheerio=require('cheerio');
const bencode=require('bncode');
const crypto=require('crypto');
const http=require('http');
const https=require('https');

const PORT=Number(process.env.PORT||7000);
const BASE='https://sktorrent.eu';
const SEARCH=`${BASE}/torrent/torrents_v2.php`;
const TTL=Number(process.env.CACHE_TTL_SECONDS||600)*1000;
const META_TTL=6*60*60*1000;
const PAGE_SIZE=40;
const CONCERT_CAT=26;
const cache=new Map();
const httpAgent=new http.Agent({keepAlive:true,maxSockets:30});
const httpsAgent=new https.Agent({keepAlive:true,maxSockets:30});

const CATS=[
['movie','skt-novinky-dabing-filmy','🆕 SKT: Novinky CZ/SK dabing – filmy'],
['series','skt-novinky-dabing-serialy','🆕 SKT: Novinky CZ/SK dabing – seriály'],
['series','skt-serialy-czsk','🇨🇿🇸🇰 SKT: Seriály – CZ/SK dabing'],
['movie','skt-4k-uhd-czsk','💎 SKT: 4K / UHD CZ/SK'],
['movie','skt-filmove-novinky','🎬 SKT: Filmové novinky'],
['movie','skt-posledne-filmy','🕒 SKT: Posledné pridané filmy'],
['series','skt-posledne-serialy','🕒 SKT: Posledné pridané seriály'],
['movie','skt-nove-koncerty','🎤 SKT: Nové koncerty'],
['movie','skt-posledne-koncerty','🎶 SKT: Posledné pridané koncerty'],
['movie','skt-4k-uhd-koncerty','✨ SKT: 4K / UHD koncerty']
].map(([type,id,name])=>({type,id,name}));

const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const nodiac=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const abs=u=>{try{return u?new URL(u,SEARCH).href:null}catch{return null}};
const enc=o=>Buffer.from(JSON.stringify(o),'utf8').toString('base64url');
const dec=t=>{try{return t&&t!=='default'?JSON.parse(Buffer.from(t,'base64url').toString('utf8')):{}}catch{return{}}};
const log=(...a)=>console.log(new Date().toISOString(),...a);
const cached=async(k,ttl,fn)=>{const h=cache.get(k);if(h&&h.e>Date.now())return h.v;const v=await fn();cache.set(k,{v,e:Date.now()+ttl});return v};
const pages=c=>Math.max(1,Math.min(20,Number(c.pages||8)||8));
function client(c={}){return axios.create({timeout:12000,maxRedirects:5,httpAgent,httpsAgent,headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36','Accept-Language':'sk,cs;q=0.9,en;q=0.7',Referer:BASE+'/',...(c.uid&&c.pass?{Cookie:`uid=${c.uid}; pass=${c.pass}`}:{})}})}
function dateFrom(t){const m=String(t).match(/Pridany\s+(\d{1,2})\/(\d{1,2})\/(\d{4})/i);return m?new Date(Date.UTC(+m[3],+m[2]-1,+m[1],12)):null}
function yearFrom(t){const y=new Date().getUTCFullYear(),a=[...String(t).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(m=>+m[1]).filter(x=>x<=y+1);return a.at(-1)||null}
function displayTitle(s){return clean(s).replace(/^Stiahni si\s*/i,'').replace(/\s*=\s*CSFD\s*\d+%.*$/i,'').trim()||'SKTorrent'}
function lookupCandidates(raw){let s=displayTitle(raw).replace(/\[[^\]]*\]/g,' ').replace(/\((?:CZ|SK|EN|CZ\/EN|SK\/EN|CZ\/SK|SK\/CZ)[^)]*\)/gi,' ').replace(/\bS\d{1,2}(?:E\d{1,3})?\b/gi,' ').replace(/\b\d{1,2}x\d{1,3}\b/gi,' ').replace(/\b(2160p|1080p|720p|4k|uhd|hdr10|hdr|dv|hevc|x265|x264|web-?dl|webrip|blu-?ray|bdrip|tvrip|remux|h\.?264|h\.?265)\b/gi,' ').replace(/\s+/g,' ').trim();const parts=s.split(/\s+\/\s+/).map(x=>x.trim()).filter(Boolean),out=[];for(const p of [...parts,s]){const q=p.replace(/\((?:19\d{2}|20\d{2})(?:\s*[-–]\s*(?:19\d{2}|20\d{2}))?\)/g,' ').replace(/\b(?:19\d{2}|20\d{2})\b/g,' ').replace(/\s+/g,' ').trim();if(q.length>1&&!out.includes(q))out.push(q)}return out.slice(0,2)}
const lookupTitle=n=>lookupCandidates(n)[0]||displayTitle(n);
function posterFromCell($,cell){let out=null;cell.find('img').each((_,im)=>{if(out)return;const el=$(im);for(const k of ['data-src','data-original','data-lazy-src','src']){const u=abs(el.attr(k));if(!u)continue;const l=u.toLowerCase();if(l.includes('/flag/')||l.includes('/flags/')||l.includes('spacer')||l.includes('pixel')||l.endsWith('.gif'))continue;out=u;break}});return out}
function parseAnchor($,el,forcedCat=0){const a=$(el),href=a.attr('href')||'',m=href.match(/[?&]id=([^&]+)/);if(!m)return null;const cell=a.closest('td');if(!cell.length)return null;const text=clean(cell.text());let category=clean(cell.find('a[href*="category="]').first().text())||clean(cell.find('b').first().text());if(!category&&forcedCat===CONCERT_CAT)category='Hudební videa';let name=clean(a.attr('title'))||clean(a.text())||clean(a.find('img').first().attr('alt'));if(!name||/^(image|cz|sk|en|de|pl|hu)$/i.test(name))return null;const d=dateFrom(text);return{id:m[1],name:displayTitle(name),category,size:(text.match(/Velkost\s*([^|]+)/i)||[])[1]?.trim()||'?',seeds:+((text.match(/Odosielaju\s*:\s*(\d+)/i)||[])[1]||0),addedDate:d,added:d?d.toISOString().slice(0,10):null,poster:posterFromCell($,cell),year:yearFrom(name),detailUrl:abs(href),downloadUrl:`${BASE}/torrent/download.php?id=${encodeURIComponent(m[1])}`}}
async function fetchPage(p,c={},category=0){const key=`page:${category}:${p}:${c.uid?String(c.uid).slice(-6):'g'}`;return cached(key,TTL,async()=>{const r=await client(c).get(SEARCH,{params:{active:0,category,order:'data',by:'DESC',page:p}}),$=cheerio.load(r.data),map=new Map();$('a[href^="details.php"]').each((_,el)=>{const x=parseAnchor($,el,category);if(!x)return;const old=map.get(x.id);if(!old||x.name.length>old.name.length||(!old.poster&&x.poster))map.set(x.id,{...old,...x})});const out=[...map.values()];log(`SKTorrent page=${p} category=${category} parsed=${out.length}`);return out})}
async function recent(c={},wanted=120,category=0){const out=[],seen=new Set();for(let p=0;p<pages(c);p++){let a=[];try{a=await fetchPage(p,c,category)}catch(e){if(!out.length)throw e;break}for(const x of a)if(!seen.has(x.id)){seen.add(x.id);out.push(x)}if((a.length<10||out.length>=Math.max(200,wanted*5))&&p>=2)break}return out.sort((a,b)=>(b.addedDate?.getTime()||0)-(a.addedDate?.getTime()||0))}
const isSeries=x=>/seri[aá]l/i.test(x.category);
const is4k=x=>/\b(2160p|4k|uhd)\b|hdr10|dolby\s*vision|\bDV\b/i.test(x.name);
function isMovie(x){const c=nodiac(x.category).toLowerCase();return !c.includes('serial')&&!c.includes('hudba')&&!c.includes('hudebni videa')&&!c.includes('dokument')&&!c.includes('tv porad')&&(c.includes('film')||c.includes('uhd')||c.includes('blu-ray'))}
function isCzSk(x){const t=`${x.category} ${x.name}`;return /filmy\s+cz\s*\/\s*sk\s+dabing/i.test(x.category)||/(?:^|[\s(\[\/_-])(CZ|SK)(?=$|[\s)\]\/, _-])/i.test(t)||/CZ\s*\/\s*(SK|EN)|SK\s*\/\s*(CZ|EN)/i.test(t)}
function isConcert(x){const c=nodiac(x.category).toLowerCase(),n=x.name;if(c.includes('hudebni videa'))return true;if(!c.includes('hudba')||/\b(flac|mp3|wavpack|wav|aac|hi-?res)\b/i.test(n))return false;return /\b(concert|koncert|live\s+(at|in)|tour|festival|unplugged|ziv[eě])\b/i.test(n)&&/\b(2160p|1080p|720p|4k|uhd|blu-?ray|web-?dl|webrip|x26[45]|mkv|mp4)\b/i.test(n)}
const fresh=(x,d=120)=>x.addedDate&&Date.now()-x.addedDate.getTime()<d*864e5;
const newRel=x=>x.year?x.year>=new Date().getUTCFullYear()-1:fresh(x);
function filter(id,a){switch(id){case'skt-novinky-dabing-filmy':return a.filter(x=>isMovie(x)&&isCzSk(x)&&newRel(x));case'skt-novinky-dabing-serialy':return a.filter(x=>isSeries(x)&&isCzSk(x)&&(fresh(x)||newRel(x)));case'skt-serialy-czsk':return a.filter(x=>isSeries(x)&&isCzSk(x));case'skt-4k-uhd-czsk':return a.filter(x=>isMovie(x)&&isCzSk(x)&&is4k(x));case'skt-filmove-novinky':return a.filter(x=>isMovie(x)&&newRel(x));case'skt-posledne-filmy':return a.filter(isMovie);case'skt-posledne-serialy':return a.filter(isSeries);case'skt-nove-koncerty':return a.filter(x=>isConcert(x)&&newRel(x));case'skt-posledne-koncerty':return a.filter(isConcert);case'skt-4k-uhd-koncerty':return a.filter(x=>isConcert(x)&&is4k(x));default:return[]}}
function seriesKey(n){return nodiac(lookupTitle(n)).toLowerCase().replace(/\b\d+\.?\s*(serie|seria|series|season)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function groups(a){const m=new Map();for(const x of a){const k=seriesKey(x.name);if(!k)continue;if(!m.has(k))m.set(k,{key:k,name:lookupTitle(x.name)||x.name,items:[]});m.get(k).items.push(x)}return[...m.values()]}
function episode(n){const s=nodiac(n);let m=s.match(/\bS(\d{1,2})[ ._-]*E(\d{1,3})\b/i);if(m)return{season:+m[1],episode:+m[2]};m=s.match(/\b(\d{1,2})x(\d{1,3})\b/i);return m?{season:+m[1],episode:+m[2]}:{season:null,episode:null}}
function baseUrl(req){return String(process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'')}
const fallbackPoster=(req,t)=>`${baseUrl(req)}/poster.svg?title=${encodeURIComponent(t||'SKTorrent')}`;
function movieMeta(req,x,concert=false){const name=displayTitle(x.name);return{id:`${concert?'sktc':'skt'}:${x.id}`,type:'movie',name,poster:x.poster||fallbackPoster(req,name),posterShape:'poster',description:[x.category,x.added&&`Pridané ${x.added}`,x.size,`${x.seeds} seed`].filter(Boolean).join(' • '),releaseInfo:x.year?String(x.year):x.added||undefined,genres:concert?['Concert']:undefined,behaviorHints:{defaultVideoId:`${concert?'sktc':'skt'}:${x.id}`}}}
function seriesMeta(req,g){const x=g.items[0];return{id:`sktseries:${Buffer.from(g.key).toString('base64url')}`,type:'series',name:g.name,poster:x.poster||fallbackPoster(req,g.name),posterShape:'poster',description:`SKTorrent • ${g.items.length} torrentov`,releaseInfo:x.year?String(x.year):x.added||undefined}}
const nm=s=>nodiac(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
function hitYear(h){return +((String(h.releaseInfo||h.year||'').match(/\b(19\d{2}|20\d{2})\b/)||[])[1]||0)||null}
function pickHit(arr,q,y){const nq=nm(q);let best=null,score=-1;for(const h of arr||[]){const hn=nm(h.name||h.title);let s=hn===nq?100:(hn.includes(nq)||nq.includes(hn)?65:0);const hy=hitYear(h);if(y&&hy)s+=Math.abs(y-hy)<=1?25:-25;if(h.poster)s+=5;if(s>score){score=s;best=h}}return score>=40?best:null}
async function cinemeta(meta,x,type){const qs=lookupCandidates(x.name);return cached(`cine:${type}:${x.year||''}:${qs.join('|').toLowerCase()}`,META_TTL,async()=>{for(const q of qs){try{const r=await axios.get(`https://v3-cinemeta.strem.io/catalog/${type==='series'?'series':'movie'}/top/search=${encodeURIComponent(q)}.json`,{timeout:4500}),h=pickHit(r.data?.metas,q,x.year);if(h)return{...meta,poster:h.poster||meta.poster,background:h.background||meta.background,description:h.description||meta.description,releaseInfo:h.releaseInfo||meta.releaseInfo,imdbRating:h.imdbRating||meta.imdbRating}}catch(e){log('Cinemeta',q,e.message)}}return meta})}
async function tmdb(meta,x,type,c){const key=c.tmdbKey||process.env.TMDB_API_KEY;if(!key)return meta;for(const q of lookupCandidates(x.name)){try{const t=type==='series'?'tv':'movie',yr=type==='series'?'first_air_date_year':'year',r=await axios.get(`https://api.themoviedb.org/3/search/${t}`,{timeout:5000,params:{api_key:key,query:q,language:'cs-CZ',include_adult:false,...(x.year?{[yr]:x.year}:{})}}),h=r.data?.results?.[0];if(h){const date=h.release_date||h.first_air_date;return{...meta,name:h.title||h.name||meta.name,poster:h.poster_path?`https://image.tmdb.org/t/p/w500${h.poster_path}`:meta.poster,background:h.backdrop_path?`https://image.tmdb.org/t/p/original${h.backdrop_path}`:meta.background,description:h.overview||meta.description,releaseInfo:date?.slice(0,4)||meta.releaseInfo,imdbRating:h.vote_average?Number(h.vote_average).toFixed(1):meta.imdbRating}}}catch(e){log('TMDB',q,e.message)}}return meta}
async function enrich(meta,x,type,c){const before=meta.poster,t=await tmdb(meta,x,type,c);if(t.poster&&t.poster!==before)return t;return cinemeta(t,x,type)}
async function mapLimit(a,n,fn){const out=new Array(a.length);let i=0;async function w(){for(;;){const j=i++;if(j>=a.length)return;try{out[j]=await fn(a[j],j)}catch{out[j]=a[j]}}}await Promise.all(Array.from({length:Math.min(n,Math.max(1,a.length))},w));return out}
async function torrentData(x,c){if(!c.uid||!c.pass)throw Error('Nastav SKTorrent uid/pass cez /configure.');return cached(`tor:${x.id}:${String(c.uid).slice(-6)}`,864e5,async()=>{const r=await client(c).get(x.downloadUrl,{responseType:'arraybuffer',timeout:15000}),buf=Buffer.from(r.data);if(buf.slice(0,100).toString().match(/<html|<!doctype/i))throw Error('SKTorrent vrátil HTML namiesto .torrent – skontroluj uid/pass.');const t=bencode.decode(buf),hash=crypto.createHash('sha1').update(bencode.encode(t.info)).digest('hex'),files=t.info.files?t.info.files.map((f,i)=>({index:i,path:(f['path.utf-8']||f.path||[]).map(p=>Buffer.from(p).toString()).join('/'),length:Number(f.length||0)})):[{index:0,path:Buffer.from(t.info['name.utf-8']||t.info.name||'video').toString(),length:Number(t.info.length||0)}];return{hash,files}})}
const vids=a=>a.filter(f=>/\.(mkv|mp4|avi|m4v|ts|m2ts|mov|wmv|webm)$/i.test(f.path));
async function findItem(id,c){let a=await recent(c,120,0),x=a.find(v=>v.id===id);if(x)return x;a=await recent(c,100,CONCERT_CAT);return a.find(v=>v.id===id)||null}
async function seriesVideos(g,c){const out=[],seen=new Set();for(const x of g.items.slice(0,25)){let e=episode(x.name);if(e.season&&e.episode){const k=`${e.season}:${e.episode}`;if(!seen.has(k)){seen.add(k);out.push({id:`sktv:${x.id}:${e.season}:${e.episode}`,title:`S${String(e.season).padStart(2,'0')}E${String(e.episode).padStart(2,'0')}`,season:e.season,episode:e.episode,released:x.addedDate?.toISOString()})}continue}if(c.uid&&c.pass)try{const td=await torrentData(x,c);for(const f of vids(td.files)){e=episode(f.path);if(e.season&&e.episode){const k=`${e.season}:${e.episode}`;if(!seen.has(k)){seen.add(k);out.push({id:`sktf:${x.id}:${f.index}:${e.season}:${e.episode}`,title:`S${String(e.season).padStart(2,'0')}E${String(e.episode).padStart(2,'0')}`,season:e.season,episode:e.episode,released:x.addedDate?.toISOString()})}}}}catch{}}return out.sort((a,b)=>a.season-b.season||a.episode-b.episode)}
function manifest(){return{id:'community.sktorrent.catalogs',version:'1.1.0',name:'SKTorrent Katalógy',description:'CZ/SK filmy, seriály, 4K/UHD a koncerty. Plagáty automaticky cez Cinemeta, TMDB voliteľný.',resources:[{name:'catalog',types:['movie','series']},{name:'meta',types:['movie','series'],idPrefixes:['skt:','sktc:','sktseries:']},{name:'stream',types:['movie','series'],idPrefixes:['skt:','sktc:','sktv:','sktf:']}],types:['movie','series'],catalogs:CATS.map(c=>({...c,extra:[{name:'skip',isRequired:false}]})),idPrefixes:['skt:','sktc:','sktseries:','sktv:','sktf:'],behaviorHints:{configurable:true,configurationRequired:false}}}
const skipOf=s=>Math.max(0,+((decodeURIComponent(String(s||'')).match(/skip=(\d+)/)||[])[1]||0));
async function catalog(req,res,c){const spec=CATS.find(x=>x.type===req.params.type&&x.id===req.params.id);if(!spec)return res.status(404).json({metas:[]});const sk=skipOf(req.params.extra),cat=spec.id.includes('koncert')?CONCERT_CAT:0,raw=await recent(c,sk+PAGE_SIZE,cat),a=filter(spec.id,raw);if(spec.type==='series'){const gs=groups(a).slice(sk,sk+PAGE_SIZE),metas=await mapLimit(gs,6,g=>enrich(seriesMeta(req,g),g.items[0],'series',c));return res.json({metas})}const concert=spec.id.includes('koncert'),vis=a.slice(sk,sk+PAGE_SIZE),metas=await mapLimit(vis,6,x=>enrich(movieMeta(req,x,concert),x,'movie',c));res.json({metas})}
async function meta(req,res,c){const{id,type}=req.params;if(type==='movie'&&(id.startsWith('skt:')||id.startsWith('sktc:'))){const x=await findItem(id.split(':')[1],c);return res.json({meta:x?await enrich(movieMeta(req,x,id.startsWith('sktc:')),x,'movie',c):null})}if(type==='series'&&id.startsWith('sktseries:')){let k='';try{k=Buffer.from(id.slice('sktseries:'.length),'base64url').toString()}catch{}const g=groups(await recent(c,240,0)).find(z=>z.key===k);if(!g)return res.json({meta:null});let m=await enrich(seriesMeta(req,g),g.items[0],'series',c);m={...m,videos:await seriesVideos(g,c)};return res.json({meta:m})}res.json({meta:null})}
async function stream(req,res,c){if(!c.uid||!c.pass)return res.json({streams:[{name:'SKTorrent – konfigurácia',title:'Nastav uid/pass cez /configure.',externalUrl:`${baseUrl(req)}/configure`} ]});const p=req.params.id.split(':'),kind=p[0],tid=p[1],x=await findItem(tid,c);if(!x)return res.json({streams:[]});try{const td=await torrentData(x,c),vf=vids(td.files);let f;if(kind==='sktf')f=td.files.find(z=>z.index===+p[2]);else if(kind==='sktv'){const s=+p[2],e=+p[3];f=vf.find(z=>{const q=episode(z.path);return q.season===s&&q.episode===e})}f=f||[...vf].sort((a,b)=>b.length-a.length)[0];if(!f)return res.json({streams:[]});res.json({streams:[{name:`SKTorrent • ${is4k(x)?'4K/UHD':/1080p/i.test(x.name)?'1080p':/720p/i.test(x.name)?'720p':'Video'}`,title:`${x.name}\n${x.size} • ${x.seeds} seed`,infoHash:td.hash,fileIdx:f.index,behaviorHints:{filename:f.path,bingeGroup:`skt-${tid}`}}]})}catch(e){res.json({streams:[{name:'SKTorrent – chyba',title:e.message,externalUrl:`${baseUrl(req)}/configure`} ]})}}

const app=express();app.set('trust proxy',1);app.use(cors());app.use(express.urlencoded({extended:true}));app.use(express.json());
app.get('/health',(_q,r)=>r.json({ok:true,addon:'SKTorrent Katalógy',version:'1.1.0',catalogs:CATS.length,at:new Date().toISOString()}));
app.get('/poster.svg',(q,r)=>r.type('svg').send(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900"><rect width="100%" height="100%" fill="#171717"/><text x="300" y="390" text-anchor="middle" fill="white" font-family="Arial" font-size="42" font-weight="700">SKTorrent</text><text x="300" y="450" text-anchor="middle" fill="#ddd" font-family="Arial" font-size="20">${esc(String(q.query.title||'').slice(0,42))}</text></svg>`));
app.get('/configure',(req,res)=>{const base=baseUrl(req);res.type('html').send(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{font:16px system-ui;background:#101114;color:#eee;max-width:720px;margin:35px auto;padding:18px}input,button{width:100%;box-sizing:border-box;padding:12px;margin:6px 0 15px;border-radius:9px}input{background:#1b1d22;color:#fff;border:1px solid #444}button{font-weight:700}code{word-break:break-all}</style><h1>SKTorrent Katalógy v1.1</h1><p>uid/pass sú potrebné na prehrávanie. Plagáty sa skúšajú automaticky cez Cinemeta; TMDB key je voliteľný a pridá lepšie CZ metadata.</p><input id=u placeholder="uid"><input id=p type=password placeholder="pass"><input id=t type=password placeholder="TMDB API key (voliteľné)"><input id=pg type=number min=1 max=20 value=8><button onclick="go()">Vytvoriť manifest</button><p id=o></p><script>function go(){let c={uid:u.value.trim(),pass:p.value.trim(),tmdbKey:t.value.trim(),pages:+pg.value||8},x=btoa(unescape(encodeURIComponent(JSON.stringify(c)))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,''),m='${base}/'+x+'/manifest.json';o.innerHTML='<a href="stremio://'+m.replace(/^https?:\\/\\//,'')+'">Inštalovať do Stremio</a><br><br><code>'+m+'</code>'}</script>`)});
app.get('/manifest.json',(_q,r)=>r.json(manifest()));app.get('/:token/manifest.json',(_q,r)=>r.json(manifest()));
for(const pre of ['', '/:token']){app.get(`${pre}/catalog/:type/:id.json`,async(q,r)=>{try{await catalog(q,r,pre?dec(q.params.token):{})}catch(e){log('catalog',e.message);r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/catalog/:type/:id/:extra.json`,async(q,r)=>{try{await catalog(q,r,pre?dec(q.params.token):{})}catch(e){log('catalog',e.message);r.status(502).json({metas:[],error:e.message})}});app.get(`${pre}/meta/:type/:id.json`,async(q,r)=>{try{await meta(q,r,pre?dec(q.params.token):{})}catch(e){r.status(502).json({meta:null,error:e.message})}});app.get(`${pre}/stream/:type/:id.json`,async(q,r)=>{try{await stream(q,r,pre?dec(q.params.token):{})}catch(e){r.status(502).json({streams:[],error:e.message})}})}
app.get('/debug/concerts',async(_q,r)=>{try{const a=await recent({},40,CONCERT_CAT);r.json({ok:true,category:CONCERT_CAT,parsed:a.length,recognized:a.filter(isConcert).length,sample:a.slice(0,5).map(x=>({id:x.id,name:x.name,category:x.category,poster:!!x.poster,added:x.added}))})}catch(e){r.status(502).json({ok:false,error:e.message})}});
app.get('/',(_q,r)=>r.redirect('/configure'));
app.listen(PORT,()=>{log(`SKTorrent addon v1.1 listening on ${PORT}`);setTimeout(async()=>{try{const a=await fetchPage(0,{},CONCERT_CAT);log(`Concert self-test parsed=${a.length} recognized=${a.filter(isConcert).length} sample=${a.slice(0,3).map(x=>x.name).join(' | ')}`)}catch(e){log('Concert self-test failed',e.message)}},1500)});
